### PR TITLE
chore: Show link to guide on Jira auth popup close

### LINKED ISSUE #7756: Bug: Jira Integration - grayed out "Authorize" button
A [customer](https://app.hubspot.com/contacts/3888472/contact/98419001) 🔒 emailed Support:
Screenshot 2023-02-02 at 11 00 46 PM

Another [customer](https://app.hubspot.com/contacts/3888472/contact/80280951) reported the same issue in the same week:
Screenshot 2023-02-02 at 11 03 06 PM

Escalating this issue to p1 per the recommendation of @nickoferrall, as the first customer noted is on a paid plan.

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Fixes #7756 
When the user closes the popup without finishing authorization for Jira, show an error message with a link to our troubleshooting guide.

## Demo

https://www.loom.com/share/6bfa60b7e9ee42f2b9f8231a1d59d85b?sid=da869b36-7d01-4856-9006-8bc93b7bc211

## Testing scenarios

- try integrating from integration settings, Sprint Poker, task dashboard
- close the popup
- see the error

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by Dschoordsch** [comment]
@acressall This is how the error looks like:
Screenshot 2023-09-21 at 10 14 17
Screenshot 2023-09-21 at 11 07 45
Do I need to change anything?

**Comment by acressall** [comment]
I like this! The sprint poker version is fine ✅ 
For the settings version, I'd just like the text to be aligned with the rest of the text
integration error

**Comment by acressall** [comment]
One other question: what happens if I don't try again, but leave the page. Will the error still be there when I come back? (I would expect it to be back in the default state)

**Review by igorlesnenko — APPROVED** [review]

**Comment by Dschoordsch** [comment]
> One other question: what happens if I don't try again, but leave the page. Will the error still be there when I come back? (I would expect it to be back in the default state)

Yes, like other errors in the app, the message vanishes if you leave the page, so it's back to a clean state next time.

**Pull request merged**
