### PR TITLE
Poker template scale UI

### PR DESCRIPTION
**Pull request by tianrunhe**
Implements #4328 

#### Scale:
- [ ] User can create their own scale
- [ ] User can clone from a default scale
- [ ] User can set a scale for a dimension
- [ ] User can delete their team scales; Deleting a scale will make all dimensions using that scale falls back to Fibonacci scale

#### Scale Value:
- [ ] A scale value option has a value field and a color
- [ ] A scale value option can be added, edited, deleted and moved
- [ ] User cannot create duplicate scale values; label cannot exceed 2 characters
- [ ] The scale editing view goes back to the template details view

### CODE REVIEW

**Comment by ackernaut** [comment]
### Test cycle no. 1
#### Scale:
- [ ] User can create their own scale
- [ ] User can clone from a default scale
- [ ] User can set a scale for a dimension
- [ ] User can delete their team scales; Deleting a scale will make all dimensions using that scale falls back to Fibonacci scale

#### Scale Value:
- [ ] A scale value option has a value field and a color
- [ ] A scale value option can be added, edited, deleted and moved
- [ ] User cannot create duplicate scale values; label cannot exceed 2 characters
- [ ] The scale editing view goes back to the template details view

**Comment by ackernaut** [comment]
## List WIP
### Refine UI styles:
- [ ] Scale editor header, label and back control
- [ ] Scale item icon controls
### Nuances
- [ ] Typing 55 throws an error that won’t go away because 5 already exists, the error could go away once the second 5 is typed

**Comment by ackernaut** [comment]
@tianrunhe This is really good work. All of the test actions look good. Besides a few small UI style improvements, there are some funky behaviors with the error checking, blurring, submitting, and dragging. Also, there are some nuances with the menu item highlighting. See above and feel free to ask questions.

**Review by ackernaut — CHANGES_REQUESTED** [review]
- [x] Smooth out the input interaction (checking for errors on keystroke? blurring, dragging, submitting?)
- [x] Fix the menu highlighting
- [x] Address styling (if it’s quirky I can take a look at it)

**Comment by tianrunhe** [comment]
Hey @ackernaut please take another round of look, thx a lot!

**Comment by ackernaut** [comment]
### Test cycle no. 2
#### Scale:
- [ ] User can create their own scale
- [ ] User can clone from a default scale
- [ ] User can set a scale for a dimension
- [ ] User can delete their team scales; Deleting a scale will make all dimensions using that scale falls back to Fibonacci scale

#### Scale Value:
- [ ] A scale value option has a value field and a color
- [ ] A scale value option can be added, edited, deleted and moved
- [ ] User cannot create duplicate scale values; label cannot exceed 2 characters
- [ ] The scale editing view goes back to the template details view

**Review by ackernaut — APPROVED** [review]
Nice work @tianrunhe this LGTM. I pushed a small bit of style refinement.

There are two things to note that I have low tension about:
- When editing a scale and closing the dialog, the dialog opens up again to the scale details view. At first, I expected it to open up to the selected template details view. After second thought, I’m okay opening up to the last view seen.
- When editing a scale it’s possible to navigate to other scales or tabs. The scale details view remains active. It’s strange to hit the back button in the scale details view and go to a different template that has now been selected. I don’t think this is a likely use case, and folks can probably find their way back. One option could be that we swap the scale details view for the template details view of the newly selected template when using the left nav.

**Comment by tianrunhe** [comment]
@mattkrick feature/UI test completed, please do code review. Thanks!

**Comment by mattkrick** [comment]
starting review...

**Comment by tianrunhe** [comment]
@mattkrick Ready for another look! I suspect if there are still some tiny issues but should be good for beta release.

**Comment by mattkrick** [comment]
lookin sharp! just gonna fix up a couple tiny things & then ship this sucker out

**Comment by mattkrick** [comment]
merging to master, will pick up the polish in https://github.com/ParabolInc/parabol/pull/4435

**Pull request merged**
