### PR TITLE
Zapatos orguser audit

### PR DESCRIPTION
**Pull request by tiffanyhan**

### CODE REVIEW

**Comment by tiffanyhan** [comment]
hey @mattkrick this is an alt PR for postgres api using zapatos. would love to discuss more in depth 1v1

**Comment by mattkrick** [comment]
closing in favor of the pgtyped PR

**Comment by jgonera** [comment]
@mattkrick @tiffanyhan Sorry for stalking, but would you mind sharing a summary of why you went with pgtyped and not zapatos? Asking because I'm considering using one of them for a project.

Thank you for developing Parabol so openly!

**Comment by mattkrick** [comment]
hi @jgonera! both have some sharp edges, but the reasoning for picking pgtyped is here: https://github.com/ParabolInc/parabol/issues/4554#issuecomment-771311892

**Pull request closed without merging**
