### PR TITLE
fix: prevent virtual keyboard hiding after submitting a comment on mobile

### LINKED ISSUE #7165: Send button is disabled in retro discussion on mobile
## Issue - Bug
Send button is disabled on mobile. However, we can send using the keyboard arrow/next-line button. I think it should be similar to the desktop version and the next-line button should work as next line button 

Apart from that clicking on the send button also closes the keyboard which is also annoying. 

#### Desktop
Screenshot 2022-09-09 224844

#### Mobile
https://user-images.githubusercontent.com/106697681/189408259-3ed76f93-08f0-47df-9ce0-306b0c3027e1.mp4

- **How serious is the bug?** P4
- **OS:**  Android
- **Browser:** Chrome 

### Acceptance Criteria (optional)
- User can send the comment using the send button
- Clicking the send button should not close the keyboard
- Next-line button should change the line (instead of sending comment) as there is no other way on mobile to change the line.

### PR DESCRIPTION
**Pull request by gitstart-parabol**
# Description
Partially fixes #7165
This is a follow-up PR for [pull:7361](https://github.com/ParabolInc/parabol/pull/7361) that fixes the issues listed below, with reference from [this](https://github.com/ParabolInc/parabol/pull/7361#discussion_r1018006945) discussion.

- [x] Clicking the send button should not close the keyboard
- [x] Next-line button should change the line (instead of sending comment) as there is no other way on mobile to change the line.

## Demo
https://user-images.githubusercontent.com/34602861/199014360-62b3df67-8322-4a8b-91f8-db44523fce69.mov

## Testing scenarios

- [ ] Scenarios
  - Start the server locally and go to any app page from an  android device
  - Create a meeting and add a comment to the meeting
  - Then reply to that comment of the meeting

## Final checklist

- [x] I checked the [code review guidelines](https://github.com/ParabolInc/parabol/docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by gitstart-parabol** [comment]
@BartoszJarocki this PR is ready for review, cc @Dschoordsch

**Review by BartoszJarocki — COMMENTED** [review]
I spent quite a bit of time playing with this problem, and what's interesting
1. iOS doesn't have that problem
2. I'm not sure what's the desired solution, as I wouldn't assume that multiline comments are something common

here's what I'd do

```
modified: packages/client/components/AndroidEditorFallback.tsx
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ packages/client/components/AndroidEditorFallback.tsx:83 @ const AndroidEditorFallback = (props: Props) => {
      onFocus={onFocus}
      onPaste={handlePaste}
      onKeyDown={onKeyDown}
      +inputMode='text'
      +enterKeyHint='done'
    />
  )
}
```

This means, virtual keyboard (on Android, as iOS will most probably still show `Enter`) will show `Send` instead of enter, making it easier to submit a comment. With that in place, I'd not worry about `Send` button hiding the virtual keyboard. Anyway, I tested the PR and everything seems to be working ok. @mattkrick do you mind taking a look? I'm not sure what's the expected behavior here.

**Comment by gitstart-parabol** [comment]
> I spent quite a bit of time playing with this problem, and what's interesting
> 
> 1. iOS doesn't have that problem
> 2. I'm not sure what's the desired solution, as I wouldn't assume that multiline comments are something common
> 
> here's what I'd do
> 
> ```
> modified: packages/client/components/AndroidEditorFallback.tsx
> ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> @ packages/client/components/AndroidEditorFallback.tsx:83 @ const AndroidEditorFallback = (props: Props) => {
>       onFocus={onFocus}
>       onPaste={handlePaste}
>       onKeyDown={onKeyDown}
>       +inputMode='text'
>       +enterKeyHint='done'
>     />
>   )
> }
> ```
> 
> This means, virtual keyboard (on Android, as iOS will most probably still show `Enter`) will show `Send` instead of enter, making it easier to submit a comment. With that in place, I'd not worry about `Send` button hiding the virtual keyboard. Anyway, I tested the PR and everything seems to be working ok. @mattkrick do you mind taking a look? I'm not sure what's the expected behavior here.

Yes @BartoszJarocki, based on the reported issue [here](https://github.com/ParabolInc/parabol/issues/7165), this seems to be an Android issue and this PR is mainly dealing with this quote from the issue description.

> Apart from that clicking on the send button also closes the keyboard which is also annoying.

**Comment by gitstart-parabol** [comment]
Hi @mattkrick, what's the verdict on this?

**Comment by mattkrick** [comment]
only tested on the chrome emulated (without IME) but it's working as intended. LGTM!

**Pull request merged**
