### PR TITLE
Prevent remote reflection from loosing its position when opening spotlight

### LINKED ISSUE #5415: Dropping remote reflection loses position when opening the Spotlight
To reproduce:

- Go to the grouping stage in a retro
- Open a second browser and drag and drop a reflection
- On the first browser, click the open spotlight icon before the remote reflection has completely dropped
- Note that it either loses its position or moves into the Spotlight

### AC

- [ ] The dropping remote reflection position doesn't change when opening the Spotlight

### PR DESCRIPTION
**Pull request by BartoszJarocki**
Fixes #5415 

@nickoferrall seems like the root cause was pretty trivial. I went through the flow of dragging the remote reflection and it was only a matter of a wrong check if the spotlight is opened. Do you mind taking a look? 🙏 
CleanShot 2021-10-13 at 16 16 29
l

### CODE REVIEW

**Comment by nickoferrall** [comment]
Hey @BartoszJarocki, while everything was looking wonderful when we chatted earlier, I'm now seeing some spooky behaviour on my side 👻  
Here's a Loom of what I'm seeing. Please let me know if you're able to reproduce it: https://www.loom.com/share/b36ad857a1dd448bb71071c9c8829b5a

**Comment by mattkrick** [comment]
@BartoszJarocki ready for merging! Looks like we picked up a few merge conflicts. could you sort these out & merge to master when ready?

moving to self-review, feel free to merge to master

**Comment by BartoszJarocki** [comment]
@mattkrick sure, I've fixed the conflicts but the commit history on this branch is messed up so I'll just submit another PR with a tiny fix and one commit. Seems like the spotlight changed a lot since this fix came was made!

**Comment by BartoszJarocki** [comment]
Closed in favor of https://github.com/ParabolInc/parabol/pull/5624

**Pull request closed without merging**
