### PR TITLE
fix(Jira): Link to documentation if we cannot find a story point field

### LINKED ISSUE #7206: Jira: refactor voting field
As a Sprint Poker facilitator I want to be able to vote to the correct field. I only want to see fields which are actually available, even if these differ between issue types.

1) Right now we're reading the "available" fields from the schema with `expand=schema` on [get issue](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-get)). This also contains fields which might not be available (like "Story Points" or "Work Ration") we switch to explicitly read the `editmeta` information with [get editmeta](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-editmeta-get) which contains only fields which are available to edit.
These can also be retrieved with `expand=editmeta`.
This approach will show far fewer fields and will also hide "Story Points"/"Story Point estimates" if it is not available.
Special handling is necessary for time tracking fields (Original estimate, remaining estimate) which are treated special by Jira and need to be checked separately (one of these variations is set by roughly 60 users atm.)
2) Since we hopefully hide "Story Points"/"Story point estimate" with this new implementation, we should modify the drop down to add a more explaining "Are you missing a story point field? We can try to fix it" to run the current fix flow.
3) The automatic fix screen should link to the manual guide

Relates to #6887, #6589

## Acceptance criteria
* [ ] read field metadata via editmeta
* [ ] store voting field per issue type
  * [ ]  move Jira voting field out of Team in separate table
* [ ] allow user to trigger autofix if no variation of "Story Points" is available
* [ ] link Jira guides how to enable estimate features

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Partially Fixes #7206
Part 3/3

Link to external instructions if we cannot find a story points field. The link is shown in the field dropdown and links to 2 different sites for company or team managed project, based on their settings.

## Demo

https://www.loom.com/share/6a11dac79aad413dac904eaf87642626

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] company managed project
  - issue type with "Story points" or "story point estimate" field in sprint poker
  - [ ] no hint is shown

- [ ] company managed project
  - issue type without "Story points" or "story point estimate" field in sprint poker
  - [ ] hint is shown and links to **company** managed instructions

- [ ] team managed project
  - issue type with "Story points" or "story point estimate" field in sprint poker
  - [ ] no hint is shown

- [ ] team managed project
  - issue type without "Story points" or "story point estimate" field in sprint poker
  - [ ] hint is shown and links to **team** managed instructions

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by Dschoordsch** [comment]
@ackernaut  I opted to show an extra menu entry when a story point field is not present with a link to 1 of 2 instructions. Could you take a look if that's ok design wise?
Screenshot from 2022-10-13 14-29-37
Screenshot from 2022-10-13 14-29-28

**Comment by Dschoordsch** [comment]
@tianrunhe I'm pretty sure we want to track when the user presses this link. Any recommendations for event name and content?

**Comment by tianrunhe** [comment]
> @tianrunhe I'm pretty sure we want to track when the user presses this link. Any recommendations for event name and content?

For sure, how about this?

Event name: `Jira Missing Field Doc Link Clicked` (prefer long but more explanatory name than short but ambiguous ones)
Properties:
- `meetingId`
- `teamId`
- `taskId`
- `scope`: `TEAM` or `COMPANY`

**Review by igorlesnenko — APPROVED** [review]
It works!

**Comment by Dschoordsch** [comment]
> @ackernaut I opted to show an extra menu entry when a story point field is not present with a link to 1 of 2 instructions. Could you take a look if that's ok design wise? Screenshot from 2022-10-13 14-29-37 Screenshot from 2022-10-13 14-29-28

@enriquesanchez since Terry is out, could you take a look at this question?

**Comment by enriquesanchez** [comment]
@Dschoordsch What happens when the user selects "Where is my field?"

**Comment by Dschoordsch** [comment]
> @Dschoordsch What happens when the user selects "Where is my field?"

An external page with instructions opens, similar to these
* https://parabol.notion.site/Estimation-for-a-company-managed-project-ff5cd850bfb543c8818f298c16d742cf
* https://parabol.notion.site/Estimation-for-a-team-managed-project-54a428827a914029918dae1bf9c8a95d
depending on whether it's a team or company managed project.

**Review by tianrunhe — APPROVED** [review]
Sign off from metrics side

**Comment by enriquesanchez** [comment]
@Dschoordsch Got it, thanks for clarifying. 

In that case, I suggest we add an icon to indicate that the option will open an external tab/window, something like this:

imagen

I'm using the icon `open_in_new`

**Comment by Dschoordsch** [comment]
@enriquesanchez The menu is normally a bit narrower, should I add padding to make it look closer to your design?

Screenshot from 2022-10-17 21-12-40
Screenshot from 2022-10-17 21-12-29

**Comment by enriquesanchez** [comment]
>should I add padding to make it look closer to your design?

@Dschoordsch I think what you shared is fine 👍

**Pull request merged**
