### PR TITLE
feat(rid): Clone template

### PR DESCRIPTION
**Pull request by jmtaber129**
# Description

Fixes https://github.com/ParabolInc/parabol/issues/8024

~Needs rebase once https://github.com/ParabolInc/parabol/pull/8027 lands~

Enable cloning templates from the Activity Library Details view.

**Note to maintainer reviewer:** This slightly relaxes the backend permissions for cloning. Previously, a user could only clone a template if a) it's team-scoped and they're on that team, or b) it's org-scoped and the cloning team is in the org, or c) it's public. This PR changes (b) to only require that the user is in the org. This means templates could be cloned across orgs. Alternatively, we could revert the backend permission changes, and only support cloning within an org.

## Demo
https://www.loom.com/share/ce0ef593692c42258a3dd2da1152c445

## Testing scenarios

- [ ] Clone edit templates for the following scenarios:
  - [ ] Team-scoped template copied to the same team
  - [ ] Team-scoped template copied to a team within the same org
  - [ ] Team-scoped template copied to a team in a different org
  - [ ] Org-scoped template copied to the same team
  - [ ] Org-scoped template copied to a team within the same org
  - [ ] Org-scoped template copied to a team in a different org
  - [ ] Public template
- [ ] Smoke test local updates (e.g. cloned templates appear in the grid view without refresh)
- [ ] (regression test) Create a retro activity from a category view.

## Final checklist

- [X] I checked the [code review guidelines](../docs/codeReview.md)
- [X] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [X] I have performed a self-review of my code, the same way I'd do it for any other team member
- [X] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [X] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [X] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [X] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by mattkrick** [comment]
good call on the laxed permissions!

I think we could improve the UX in 1 of 2 ways:
- Assume the same teamId as the parent & skip the pick team modal, they can change that after creation
- Keep the team picker modal, but default to the current team instead of defaulting to the top one in the list

When we clone should we default the sharing level to "Organization"?

**Comment by jmtaber129** [comment]
@mattkrick We don't currently have a mutation to transfer ownership of a template, so supporting (1) would increase the scope here substantially.

Re: (2) - I'd generally expect users to want to clone templates to _different_ teams, rather than copying to the same team and then tweaking. FWIW the default team logic here is the same as the team picker on the `/new-meeting` view.

I do think we should apply one of these _eventually_, but we should kick that can down the road until we have a working thing that we can iterate on.

> When we clone should we default the sharing level to "Organization"?
I think probably yes, but since that adds a small amount of complexity (we'd need to either modify the mutation or add a call to `UpdateTemplateScope` immediately after creation) and we're still discussing the broader UX around this, I'd prefer to keep the logic as-is to mirror the existing New Meeting view's behavior around template cloning.

**Comment by mattkrick** [comment]
> I think probably yes, but since that adds a small amount of complexity (we'd need to either modify the mutation or add a call to UpdateTemplateScope immediately after creation) and we're still discussing the broader UX around this, I'd prefer to keep the logic as-is to mirror the existing New Meeting view's behavior around template cloning.

Totally agree, if there's any question it's fine to hold off. In this case I think making new/cloned templates default to org permissions is pretty stable though, but I'll default to @ackernaut. Should only be 1 line of code to fix

**Comment by ackernaut** [comment]
Yes, defaulting the template sharing to the org level is still the plan. If that slows us down in the short term, I’m okay deferring. In that case I think we would open an implementation issue to make the changes to the default that we can tackle later?

**Comment by mattkrick** [comment]
yeah, as long as we don't forget to get it in before GA I'm fine with whatever! there's a merge conflict, but withstanding that this PR is g2g

**Pull request merged**
