### PR TITLE
feat: update dashboard nav item styles

### PR DESCRIPTION
**Pull request by nickoferrall**
Fix: https://github.com/ParabolInc/parabol/issues/9790

Loom demo: https://www.loom.com/share/f2221c8aa804425791a442528c68bddb

Screenshot 2024-05-29 at 15 00 03

Do not merge this PR. I'll add further PRs to update the styles elsewhere, including mobile. 

### To test

- [x] Go to the dashboard on desktop and see that the UI looks like the designs

### CODE REVIEW

**Comment by nickoferrall** [comment]
Do not merge this PR. I'll add further PRs to update the styles elsewhere, including mobile.

**Comment by nickoferrall** [comment]
@ackernaut nope, nothing else needed here. I'm moving on to the next issue in the milestone. I'll merge this once the other PRs are all ready

**Review by ackernaut — APPROVED** [review]
I think this is in the right direction. I don’t know if you want to handle mobile styles just yet, but there’s a later of responsive styles that still need to be addressed at least to make the main nav section follow design. Happy to look at that, too!

**Comment by nickoferrall** [comment]
For sure, I was planning on tackling that in a later PR. I wanted to keep this as small as possible

**Comment by nickoferrall** [comment]
Hey @ackernaut, this is the PR with the changes. If you're happy with it, we can merge to master and ship it to users!

**Review by ackernaut — CHANGES_REQUESTED** [review]
Hey @nickoferrall ! For some reason I don’t think the series of PR merges worked correctly. When I run this `feat/9790/nav-item-styles` locally it looks like very few of the changes made it to this branch. Am I using the wrong branch?

Screenshot 2024-06-14 at 12 09 38

**Comment by nickoferrall** [comment]
@ackernaut did you do a `git pull` to get the latest from this branch? The same thing happened to me!

**Comment by ackernaut** [comment]
Oh 😓 I assumed this was a new branch at first, but then after seeing it was the original branch I didn’t think of that! Pulling now

**Review by ackernaut — APPROVED** [review]

**Comment by ackernaut** [comment]
@nickoferrall this looks great! Nice work! I did test it locally with a branch including the global banner and everything looked right with the banner on or off for both desktop and mobile. I spotted a missing divider in the mobile nav, so made a small commit. Ready to merge!

**Comment by nickoferrall** [comment]
Thanks for the update and all of the reviews! Excited to see this in production!

**Pull request merged**
