### PR TITLE
feat(templates): Share to org by default

### PR DESCRIPTION
**Pull request by jmtaber129**
# Description

Fixes https://github.com/ParabolInc/parabol/issues/8119

By default, share templates to org

## Demo
https://www.loom.com/share/922238657ba1460ea730674634d84356

## Testing scenarios
- [ ] On existing flow, create new template, and confirm shared to org
- [ ] On existing flow, clone template, and confirm shared to org
- [ ] On new flow, create new template, and confirm shared to org
- [ ] On new flow, clone template, and confirm shared to org

## Final checklist

- [X] I checked the [code review guidelines](../docs/codeReview.md)
- [X] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [X] I have performed a self-review of my code, the same way I'd do it for any other team member
- [X] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [X] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [X] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [X] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by mattkrick** [comment]
-1 On the existing flow, after cloning a public template, it still navigates to the "Team" templates. It should now navigate to the "Org" templates so I can see the new one.

**Comment by mattkrick** [comment]
-2 on existing view, cannot create new templates

**Review by mattkrick — CHANGES_REQUESTED** [review]
-2 fix for existing view

**Comment by jmtaber129** [comment]
> On the existing flow, after cloning a public template, it still navigates to the "Team" templates. It should now navigate to the "Org" templates so I can see the new one.

Navigating to "Team" templates is correct, because it's a team template scoped to org. A template only falls under "Org" if it belongs to a different team that's sharing the template with the org.

> on existing view, cannot create new templates

I can't repro this (see loom demo in description). Please elaborate on what you're seeing.

**Comment by mattkrick** [comment]
digging in now, could be my funky DB!

**Comment by mattkrick** [comment]
yep, that's on me. fresh DB & things are working!

**Pull request merged**
