### PR TITLE
fix: azure refresh auth

### PR DESCRIPTION
**Pull request by nickoferrall**
Fix https://github.com/ParabolInc/parabol/issues/7006

When refreshing the token, Azure returned the error `invalid_grant`. The error description said: 
`The refresh token was issued to a single page app (SPA), and therefore has a fixed, limited lifetime of 1.00:00:00, which cannot be extended. It is now expired and a new sign in request must be sent by the SPA to the sign in page`

This issue https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4104 and this [Azure doc](https://docs.microsoft.com/en-us/azure/active-directory/develop/refresh-tokens#refresh-token-lifetime) confirm that the user needs to re-auth after 24 hours. 

In this PR, I'm removing the user's stale auth if the refresh token error message is `invalid_grant`. In Sprint Poker, the user will now see Parabol's auth button instead of an empty list of issues. 

### To test

- It's a difficult one to test, but you could integrate with Azure, wait 24 hours, go to a Poker meeting and see that you need to re-auth
- After re-authenticating, you can see the issues

### CODE REVIEW

**Comment by Dschoordsch** [comment]
I think that could be a configuration issue, we shouldn't be in the SPA but in the Web App category [^1]. I don't know if that makes a difference, but we should modify our app anyways.

[^1]: https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-flows-app-scenarios

**Comment by nickoferrall** [comment]
Shouldn't we be in the SPA category though as we're using React? Also, do you happen to know where we can update the configuration in Azure - I haven't come across anything in the [azure portal](https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Authentication/appId/46eda4b2-e9f2-4c3e-acc0-4e23c09d81f1/isMSAApp~/false) yet

**Comment by Dschoordsch** [comment]
> Shouldn't we be in the SPA category though as we're using React? Also, do you happen to know where we can update the configuration in Azure - I haven't come across anything in the [azure portal](https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Authentication/appId/46eda4b2-e9f2-4c3e-acc0-4e23c09d81f1/isMSAApp~/false) yet

I thought so too (so did the MS code with folks since they especially implemented OAuth2 with PKCE for it), but reading through the linked page since we're not requesting the token from the browser but a separate backend, we fall into the regular Web App category. This might also give us greater freedom with regards to the refresh token lifetime.
I know where to change it, but it seems not to be a simple replace the SPA with Web app, maybe you could give it a try?

**Comment by nickoferrall** [comment]
I played around with the auth briefly but didn't find a solution. As I'm away from tomorrow, I've created this issue to document it: https://github.com/ParabolInc/parabol/issues/7114

We could move this PR to stuck in the meantime, but I think it's an improvement over what we currently have, so I'll request a review

**Comment by mattkrick** [comment]
:flushed: a 1 day refresh token!?!?

Yep, agreed with the conclusion, we are a "web app" as defined by them.
tbh I can't blame them, when i built the github integration I thought we wanted an oauth2 integration & we really need a "GitHub  App"

**Comment by mattkrick** [comment]
merging since this PR is better than what we currently have. the fix is gonna be moving to a webapp per #7114

**Pull request merged**
