### PR TITLE
fix: Task assignee menu is missing entries

### LINKED ISSUE #6862: Check-in: Task assignee menu is missing entries
## How to reproduce
* Start check-in meeting with 3 participants
* Try reassigning a task in Solo updates
* Try reassigning a task in Agenda item discussion

## Expected behaviour
Assignee menu shows all team members.

## Actual behaviour
Assignee menu shows different subset of members depending on stage.
Screenshot from 2022-07-07 13-37-03
Screenshot from 2022-07-07 13-34-34

### PR DESCRIPTION
**Pull request by gitstart**
# Fixed TaskAssigneeMenu
Fixed Assignee menu to show all members . Initially Assignee menu was not showing members that had been assigned tasks. 
Fixes/Partially Fixes #6862
All team members are displayed on the TaskAssigneeMenu

## Before the Bug Fixed
before

## After Bug Fixed
after

## Loom Video
https://www.loom.com/share/de0b763edc4f4eab983f5fcf1a574b68
## Testing scenarios
- [ ] Scenario A
  - Step 1
  - Start check-in meeting with 3 participants
  - Step 2...
  - Try reassigning a task in Solo updates
  - Step3
  - Try reassigning a task in Agenda item discussion

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by gitstart** [comment]
Hi @Dschoordsch, @igorlesnenko  you reviews are required for this PR

**Comment by jmtaber129** [comment]
@gitstart do y'all identify a repro for the bug described in the issue? These changes would add the current assignee to the list of possible assignees, but that alone likely wouldn't fix this bug.

**Comment by jmtaber129** [comment]
@gitstart just following up on this - without a clear repro of the bug described in the original issue, we can't confirm that these changes address the issue. Please let us know if you've found the repro steps, otherwise we'll need to close this PR.

**Comment by gitstart** [comment]
> @gitstart do y'all have a repro for the bug described in the issue? These changes would add the current assignee to the list of possible assignees, but that alone likely wouldn't fix this bug.

Yes we do, will be pushing more updates that also disable entries to the current user

**Comment by jmtaber129** [comment]
@gitstart following up on this - do you have a repro for the bug as described in https://github.com/ParabolInc/parabol/issues/6862? Note that the issue described there is different from the assigned user not appearing in the list of possible assignees - multiple users were missing from the assignee list (not just the assigned user)

**Comment by gitstart** [comment]
> #6862

Thanks for clarifying on this  @jmtaber129, we where able to make adjustments to catch `assigned user not appearing in the list` after the follow up comment of @Dschoordsch  [here](https://github.com/ParabolInc/parabol/issues/6862). will be closing this issue because its not clear.

**Pull request closed without merging**
