### PR TITLE
chore: readd gitlab feature flag

### PR DESCRIPTION
**Pull request by nickoferrall**
Lorena is off sick tomorrow so we're going to postpone launching GitLab until next week.

### CODE REVIEW

**Comment by nickoferrall** [comment]
Skipping to Maintainer Review and adding the One Request Required label as the change is small (can compare it with https://github.com/ParabolInc/parabol/pull/6554), and it's time urgent as it needs to be merged before we ship tomorrow.

**Review by BartoszJarocki — APPROVED** [review]

**Comment by Dschoordsch** [comment]
Tested, works good enough.

**Review by Dschoordsch — APPROVED** [review]

**Comment by Dschoordsch** [comment]
Merging it now as the current version on master is broken, I get
```
09:44:13 1|GraphQL Executor | GraphQLError: Cannot return null for non-nullable field UserFeatureFlags.gitlab.
09:44:13 1|GraphQL Executor |     at featureFlagsUserfeatureFlagsResolverHandler
```

**Comment by nickoferrall** [comment]
> GraphQLError: Cannot return null for non-nullable field UserFeatureFlags.gitlab. 

I initially saw that error but it went away after running `yarn && yarn dev`

**Pull request merged**
