### PR TITLE
Self hosted volume

### LINKED ISSUE #4656: Support using local avatar storage.
​

AC

- [ ] when the CDN is set to local, the directory should be mounted as a volume in the docker config so upgrading does not wipe out the avatars

​

Estimate: 4 hours

### PR DESCRIPTION
**Pull request by tiffanyhan**
Resolve #4656

The owner of a self-hosted instance can host user uploaded images in local file storage. These images should persist between upgrades and subsequent deploys.

set up steps:
- set `FILE_STORE_PROVIDER='local'` in `.env` file
- bring parabol up by calling `docker-compose -f docker-compose.yml -f ./docker/docker-compose.selfHosted.yml up -d`
- upload user and/or org images-- images should be saved in `self-hosted` folder
- stop the containers using `docker-compose down`, delete the `self-hosted` folder, and delete the image for the parabol web app
- run `docker-compose -f docker-compose.yml -f ./docker/docker-compose.selfHosted.yml up -d` again

**AC:**
- [ ] the previously uploaded images should still be accessible

### CODE REVIEW

**Comment by adaniels-parabol** [comment]
I noticed some additions for deployment outside of selfdeployment e.g. postmigrate. Are we doing this today manually? Will this break anything during deployment? @tiffanyhan

**Comment by tiffanyhan** [comment]
> I noticed some additions for deployment outside of selfdeployment e.g. postmigrate. Are we doing this today manually? Will this break anything during deployment? @tiffanyhan

yeah it's bc i recently added running postDeployMigrate script to the postdeploy command. this works for our CI and dokku deployment, but while working on this i found that it breaks the self-hosted `docker-compose` process.

solved by separating postdeploy and postmigrate into their own separate commands, and telling dokku to call both in the postdeploy hook (configured in app.json). this won't changing anything about our deployment process, it's just an equivalent refactor with separation of concerns.

**Comment by adaniels-parabol** [comment]
Do I need to add this to the k8s deployments as well?

**Comment by tiffanyhan** [comment]
@adaniels-parabol are there any changes i should make to this pr?

**Review by adaniels-parabol — APPROVED** [review]
Looks good to me.

**Comment by mattkrick** [comment]
LGTM! just a little merge conflict, but that should be an easy fix

**Pull request merged**
