### PR TITLE
feat(Retrospective): Add more prominent enter to submit hint

### PR DESCRIPTION
**Pull request by Dschoordsch**
Fixes: #6792 
This should help with onboarding new users. The hint appears after a timeout (same which is used for typing notifications) or after blurring the input.

## Demo
Peek 2022-06-21 22-43

## Testing scenarios

- Start Retrospective and go to reflect phase
- [ ] Enter text in a reflection and wait -> hint appears
- [ ] Start typing again -> hint disappears
- [ ] Blur a reflection with text -> hint appears
- [ ] Blur a reflection without text -> hint does not appear
- [ ] Blur reflection by moving focus to another window and then refocus window -> correct copy text appears
- [ ] Press the hint to submit a reflection

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by Dschoordsch** [comment]
@acressall could you take a look at the current version (see gif)? I've added an emoji to the copy as it looked a bit dry and also put some transition on it.

**Review by acressall — APPROVED** [review]

**Comment by Dschoordsch** [comment]
> Q: should/can we add this to the demo too?

It's part of the demo automatically since the demo just emulates the server side. Client side is the same as the real retrospective.

**Review by igorlesnenko — CHANGES_REQUESTED** [review]
I see some hint blinking if I click on 'Press enter to add'

https://user-images.githubusercontent.com/466991/175073782-3fb592c8-2e31-48a4-9d49-7abc244e8dc9.mov

**Comment by Dschoordsch** [comment]
@igorlesnenko fixed.

**Review by igorlesnenko — APPROVED** [review]

**Pull request merged**
