### PR TITLE
feat: add Insights UI skeleton

### PR DESCRIPTION
**Pull request by nickoferrall**
Fix https://github.com/ParabolInc/parabol/issues/10238

Screenshot 2024-09-19 at 14 30 05

This PR won't be merged until we've added the Team feature flag. 

### AC

- [ ] Click on the Insights tab and see the Insights view
- [ ] The UI looks like the design: https://www.figma.com/design/eGGewFjqfNpfU3TUgaBSDo/Insights-UI-Views?node-id=678-9563&node-type=frame&t=hRDMJwc2E81VsDVN-0

### CODE REVIEW

**Comment by nickoferrall** [comment]
Hey @ackernaut, would you mind reviewing the UI in this PR to see if it's on the right track?

I won't merge the PR until the team feature flag is ready. That way, we can release the feature to just Parabol and select teams.

**Comment by ackernaut** [comment]
Hey! I’ll take a card to review this. Thanks!

**Review by ackernaut — APPROVED** [review]
Hey Nick! Looking good. I made a small commit and PR refining a few small things. For the sheet we will end up hanging controls into a 56px left margin and I had the right margin matching since we have the space (I like the balancing effect). At some point we will also need to think about how this shrinks down responsively. I can take a task to add some mobile views in Figma.

**Comment by ackernaut** [comment]
See #10274

**Pull request merged**
