### PR TITLE
Fix #3463 lobby layout improvements

### LINKED ISSUE #3463: Meeting lobby layout
The lobby is basically laid out in 4 quadrants at laptop+ widths  but spreads out unintentionally. The original intent was to have a max height and width that centers on the page. Also at mobile widths the components will spread out vertically but this is probably only noticeable when playing with a browser viewport size.

### Acceptance Criteria
- Maxed height and width, and centered horizontally and vertically, at laptop+ breakpoints

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by ackernaut**
Fixes #3463 

### Tests
- [ ] On a small laptop viewport, the background isn’t clipped when scrolling
- [ ] On a mobile viewport, the background isn’t clipped when scrolling
- [ ] On a large display, the elements aren’t spread out across the screen; the layout is centered, reaching a max width and height

### CODE REVIEW

**Comment by ackernaut** [comment]
### Left, updated — Right, clipping
Screenshot 2020-03-04 18 15 00

### Left, clipping — Right, updated
Screenshot 2020-03-04 18 19 09

### Left, updated — Right, layout falls apart
Screenshot 2020-03-04 18 17 16

### Just right, small laptop, updated
Screenshot 2020-03-04 18 17 30

**Comment by ackernaut** [comment]
@mattkrick ready for your 👀

**Comment by mattkrick** [comment]
looks good! 1 nit-- can we center it on the screen?

Screen Shot 2020-03-11 at 4 01 25 PM
Screen Shot 2020-03-11 at 4 01 43 PM

**Comment by ackernaut** [comment]
>Can we center it on the screen?

Yeah, I wanted that, too. Let me look at it, I can’t remember why I didn’t go that route.

**Pull request merged**
