### PR TITLE
bump sharp

### LINKED ISSUE #5437: bump sharp
On m1 arm, could not start the app locally bc dependency installation was failing at sharp. bumping the package to 
^0.29.0 fixes the issue.

Reference: https://sharp.pixelplumbing.com/install#apple-m1

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

### PR DESCRIPTION
**Pull request by tiffanyhan**
Resolves #5437

Fixes an issue with installing sharp on M1 arm, thereby preventing app from starting locally

- [ ] uploading a profile image still works

### CODE REVIEW

**Comment by tiffanyhan** [comment]
@Dschoordsch mind giving this a quick test?

**Review by Dschoordsch — APPROVED** [review]
Tested with png, svg, gif and jpg, works.

**Comment by mattkrick** [comment]
ah, looks like @nickoferrall's PR bumped sharp to v0.28.0, but it didn't include pinning minipass.
Did a newer version of minipass cause a break?

**Comment by tiffanyhan** [comment]
oh great!

> ah, looks like @nickoferrall's PR bumped sharp to v0.28.0, but it didn't include pinning minipass. Did a newer version of minipass cause a break?

oh great! there was a point where i had to pin minipass to start the app locally, but i just pulled master to test and that config works well for me 🤷🏽‍♀️

**Pull request closed without merging**
