### PR TITLE
Update meeting template illustrations

### PR DESCRIPTION
**Pull request by Dschoordsch**
Resolves: #5636

### CODE REVIEW

**Review by tiffanyhan — APPROVED** [review]
lgtm! lovely to see the new illustrations

**Comment by BartoszJarocki** [comment]
Images are pixelated on my end, should we go with svg versions? 

Screenshot 2021-12-15 at 06 28 23
Screenshot 2021-12-15 at 06 29 30

**Comment by Dschoordsch** [comment]
@BartoszJarocki The images were distorted, it's fixed now.
The images have high enough resolution, if you check the files, the edges are fuzzy by design.

**Review by BartoszJarocki — APPROVED** [review]
@Dschoordsch thanks, looks nice now 👌🏻

**Comment by Dschoordsch** [comment]
I just checked the sizes, we're more than doubling the size of illustrations with this from 2.6 MB to 5.7 MB. So that might still be an argument for SVGs.

**Comment by BartoszJarocki** [comment]
Whoops, that's true! Have you checked if running the images through https://tinypng.com/ or something similar would help by any chance?

**Comment by Dschoordsch** [comment]
Thanks @BartoszJarocki for the suggestion, now we're at 3.4 MB so only an increase of 0.8 MB which seems ok.

**Comment by mattkrick** [comment]
i got the same thoughts here, vector is always preferred to keep quality high.
asked if we can get vectors here: https://github.com/ParabolInc/parabol/issues/5484#issuecomment-998320368

if that's not a possibility we can go through & merge this one, but I'd really like to stick with vectors!

**Comment by mattkrick** [comment]
stuck on: seeing if vectors are available

**Pull request merged**
