### PR TITLE
Discussion Threads

### PR DESCRIPTION
**Pull request by mattkrick**
TEST - INPUT
- [ ] clicking the comment input or the "add a task" button collapsed the "add a task" button
- [ ] when text is present in the comment input, the "add a task" button turns into a "send" button"
- [ ] can write a comment and click "send" to submit
- [ ] can write a comment and hit enter to submit

TEST - EDITOR
- [ ] can include at-mentions in your comment (start with `@`)
- [ ] can include links in your comment
- [ ] can bold/italicize your comment
- [ ] can add emojis in your comment (start with `:`)

TEST - ACTIONS
- [ ] can add a reactji to your comment
- [ ] can remove a reactji from your comment
- [ ] can click "more" to edit your comment
- [ ] can click "more" to delete your comment

TEST - SCROLL
- [ ] when there are more comments than vertical real estate & you refresh, it puts you at the bottom
- [ ] when you submit a comment, it auto scrolls to the bottom
- [ ] when someone else adds a comment & you're < 20px away from the bottom, it scrolls to bottom
- [ ] when someone else adds a comment & you're not at the bottom, it does not scroll

TEST - REPLIES
- [ ] can click Reply and see a reply input
- [ ] can submit reply with Enter or clicking send
- [ ] clicking Reply causes a scroll to show the whole input, if needed
- [ ] submitting the reply causes a scroll to show the whole comment
- [ ] can add a task as a reply & it scrolls to fit
- [ ] clicking outside a task deletes it
- [ ] clicking outside the comment input when there is no text deletes it
- [ ] when there is a partial comment, clicking out does not delete it, but clicking "Reply" somewhere else does

TEST - REPLY to REPLY
- [ ] replying to a reply makes a peer comment with a pre-populated at-mention to the author
- [ ] can hit backspace once to delete the pre-populated at-mention & then click "add a task" to add a task

TEST - ANONYMOUS
- [ ] can click your own avatar to turn into anonymous mode
- [ ] when submitting an anonymous task, it doesn't have any personal information
- [ ] when replying to an anonymous reply, it doesn't at-mention anyone

TEST - DELETE
- [ ] if a comment has a reply & you delete the comment, it turns into a tombstone
- [ ] if a task has a reply & you delete the task, the whole thread goes away (not ideal, but doing it right will take a large refactor)
- [ ] if you delete a reply, it goes away
- [ ] if you delete a reply to an already-deleted comment, they both go away

TEST - MOBILE
- [ ] in mobile mode, the reflections are in a stack, not a grid
- [ ] clicking the stack expands them
- [ ] the help FAB is not present
- [ ] on android, you can't create or edit rich-text items

TEST - DEMO
- [ ] try all the above, but in the demo

TODO
- [ ] rethink how we handle private tasks (i think being public only here is OK)
- [x] proper styles for at-mentions mid typing
- [x] rejoin facilitator sits above the add a task button

### CODE REVIEW

**Comment by mattkrick** [comment]
there's no good way to reply to a reply with a task.
eg. I create a comment that says "we need to do something about this"
then, i reply with a comment that says "everyone take a card to complete task X"
when someone clicks reply to that comment, since they are replying to a reply & we don't let them go 3 levels deep the reply is a peer that starts with an at-mention to the author.
since the at-mention exists, the "add a task" icon has changed to the "send" icon

**Comment by mattkrick** [comment]
@jordanh @ackernaut ready for testing. live on the dev server, too

**Comment by jordanh** [comment]
We'll have to figure out what to do with the "rejoin facilitator" prompt:

Screen Shot 2020-03-12 at 2 32 44 PM

**Comment by jordanh** [comment]
Here's an at-mention thingy:

gif

**Comment by ackernaut** [comment]
I think the Add Task and Toggle Anon could both use a tooltip

**Comment by jordanh** [comment]
I've got a couple of iOS styling buggies:

IMG_4649
IMG_4648

**Comment by ackernaut** [comment]
Actually the button says Add a Task until it collapses, so I think that’s safe. Also, the public/anon is a nice Snapchat/Minecraft hidden feature. So nevermind tooltips.

**Comment by mattkrick** [comment]
@jordanh for the ios bugs, can you repro in the chrome iOS browser?
if so, is it possible to reproduce in a desktop browser?

**Comment by jordanh** [comment]
@mattkrick oh yes, thank goodness Safari on OSX does the same thing if you scroll up the discuss pane

**Comment by avivapinchas** [comment]
'Publically' should be 'publicly' - that's the more common spelling. 

On small sizes, the help button overlaps the send button: 
Screen Shot 2020-03-13 at 12 51 56 PM
That's on Chrome.

**Comment by mattkrick** [comment]
> 'Publically' should be 'publicly' - that's the more common spelling.

i've been misspelling this all my life 🙈 

> On small sizes, the help button overlaps the send button:

ah shoot, i removed it for mobile devices, but i guess we'll need to handle it with a little more grace. should we just decrease the height of the discussion? what do you think would look best?

**Comment by avivapinchas** [comment]
> should we just decrease the height of the discussion? what do you think would look best?

Do you mean make the discussion column shorter, and put the help button underneath? I think that could work

**Comment by ackernaut** [comment]
A few ideas here:

- For mobile I think we should put an 8px gutter around the thread (see screenshots, one of the WIP, and one from Figma)
- For the help control I’ve been exploring it being a part of the bottom bar. I intend to make a larger proposal on updates to the meeting IA and UX that involves how new pieces get moved in including a video component. That being said I think we should make space for those pieces. The facilitator, including in the demo, can see the help menu from there. I have ideas on how participants could see this content and I wonder how much of a value it is anyway.

Screenshot 2020-03-13 16 38 23


mobile-thread-w-bottom-bar

**Comment by ackernaut** [comment]
Oooh, I still haven’t tried the Demo

**Comment by mattkrick** [comment]
i like moving it to a bottom bar, i'd be down with removing the chrome from the bottom bar & just having buttons float in a deterministic location on the bottom (down with borders/chrome 2020)

happy to ship it with a little padding on the bottom to get it out & then we can revisit control bar on another sprint

video looks siiiiick

**Comment by mattkrick** [comment]
all issues addressed, moving on to master

**Pull request merged**
