### PR TITLE
feat: add "go to dashboard" or "sign in" button to "invitation link expired" screen

### PR DESCRIPTION
**Pull request by igorlesnenko**
#6838

Authenticated user:

image

Non-authenticated user:

image

How to test:

- Pick (or make) any expired team invite link from rethinkDB `actionDevelopment.MassInvitation` (see how to make link expired here: https://github.com/ParabolInc/parabol/pull/7153#issuecomment-1265332081)
- Open incognito window with no user logged in (anonymous)
- Open the link, see an error, see `Sign in` button and suggestion to Sign in to request an invite
- Login as another user, open the link, see `Request invite` button and `My dashboard` button
- Click on Request invite, see that invite request was sent successfully

### CODE REVIEW

**Comment by enriquesanchez** [comment]
@igorlesnenko What happens if I click on the email link?

**Comment by igorlesnenko** [comment]
@enriquesanchez it is `mailto:` link

**Comment by Dschoordsch** [comment]
> @enriquesanchez it is `mailto:` link

I don't mind the `mailto:` link and it's an improvement already.

If it's easy to build I would prefer if we could send an in-app notification to the owner including an email where the owner would receive a link to a pre-filled invite team invite dialog.

**Review by nickoferrall — COMMENTED** [review]
> Pick (or make) any expired team invite link from rethinkDB actionDevelopment.MassInvitation

In rethinkdb, I can see the `expiration`, `id`, and `teamMemberId`. If I copy a mass invitation link locally from my team and change the `id` to an expired `id` from rethinkdb, I get an error message saying `The invitation token is not valid.`. 

Do you have any more details on how I can test that message?

**Comment by igorlesnenko** [comment]
@nickoferrall you can also make your existing working link expired:

If your link looks like:

http://localhost:3000/invitation-link/C32SGB55JGZ9

Run the following rethinkdb query:

```
r.db('actionDevelopment').table('MassInvitation').filter({
  id: 'C32SGB55JGZ9'
}).update({
  expiration: new Date()
})

```

Does it work for you?

**Comment by nickoferrall** [comment]
Thanks for that @igorlesnenko, that's working now!

One problem I'm noticing is after User A clicks "Request Invite" and User B accepts the invite, User A isn't added to the team. There's no change to User A's screen, even after refreshing.

**Comment by igorlesnenko** [comment]
@nickoferrall there is a bit tricky part regarding to this:

- When you click request invite — request is sent
- When someone accept the request, invitation is sent, but you are not instantly added to the team
- If you go to dashboard, and click notifications, you will see the invitation
- If you accept it, you will be added to a team.

So in order to achieve smooth flow, here we need to implement same auto-accepting invite logic as we do for meetings.

Considering this screen does not arise often:

1) I suggest to remove request invite button in this PR, to not spend time at this now.

Now it looks like:
image

2) If we ok to add such complexity to this screen, create a separate issue about this to prioritize it differently

What do you think?

**Review by nickoferrall — APPROVED** [review]
I think your point about splitting PRs makes a lot of sense 👍  I've tested it again and it LGTM!

**Review by Dschoordsch — CHANGES_REQUESTED** [review]
Please fix the PR title, otherwise looks good

**Review by Dschoordsch — APPROVED** [review]

**Pull request merged**
