### PR TITLE
Use redisLock before loading the meeting object in updatePokerScope

### LINKED ISSUE #5554: Adding Jira tasks in fast succession In Sprint Poker Scope stage is unreliable
### How to reproduce
Run a Sprint Poker and import new tasks from Jira during Scope stage in fast succession

### Expected
All tasks are added to the Estimate stage

### Actual
Some tasks seem randomly be deselected

Adding Jira tasks in fast succession

**Estimated effort:** 4 hours

### PR DESCRIPTION
**Pull request by tianrunhe**
Fixes #5554

### CODE REVIEW

**Review by igorlesnenko — CHANGES_REQUESTED** [review]
Looks like it does not fully solve the issue. I still see some lags:

https://user-images.githubusercontent.com/466991/144638101-7480da2a-9f0e-423f-a9cd-05b1bc366c32.mov

**Comment by tianrunhe** [comment]
Interesting! Is it local? I couldn't reproduce this on my local. Did you do any setup differently? @igorlesnenko

**Comment by igorlesnenko** [comment]
@tianrunhe yeah, it is local. I'm actually seeing the same behaviour both in master and in your branch. Can you reproduce the issue in master? I don't have anything special in setup.

**Comment by tianrunhe** [comment]
Weird... I can't reproduce it in either `master` or my branch:

https://www.loom.com/share/df2792c3fcfd4cc9a7264c8d43096d77

**Comment by igorlesnenko** [comment]
@tianrunhe Interesting, could it depend on performance or network? Can I help you somehow? Maybe I could try to debug on my side?

**Comment by mattkrick** [comment]
the problem might be coming from the frontend. perhaps do a 6x CPU slowdown in dev tools & see if we can reproduce?

**Pull request closed without merging**
