### PR TITLE
Remove graphql.ts

### PR DESCRIPTION
**Pull request by Dschoordsch**
graphql.ts is no longer generated since #5974. Remove references to it.

### CODE REVIEW

**Review by tianrunhe — CHANGES_REQUESTED** [review]
I got this error when running `yarn dev` and no pages can be opened...?  

```
ERROR in ./packages/server/utils/predicates.ts 3:25
Module parse failed: Unexpected token (3:25)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.
| __webpack_require__.$Refresh$.runtime = require('/Users/brucetian/Projects/parabol/node_modules/react-refresh/runtime.js');
| 
> export const isNotNull = <T>(item: T | null | undefined): item is T =>
|   item !== null && item !== undefined
| 
webpack 5.64.1 compiled with 1 error in 5515 ms
```

**Comment by Dschoordsch** [comment]
@tianrunhe I fixed the issue. It was caused by including a `.ts` file from server into client. Fixed by moving it to client.

**Review by tianrunhe — APPROVED** [review]
LGTM!

**Comment by mattkrick** [comment]
🎉

**Pull request merged**
