### PR TITLE
Remove shared templates by archived teams

### PR DESCRIPTION
**Pull request by nickoferrall**
PR for issue #4176 

### Acceptance criteria
- [ ] When a team is archived the templates that the team has shared with the org are also archived
- [ ] Existing meetings still point to the archived template

### CODE REVIEW

**Comment by mattkrick** [comment]
after the conflict looks g2g

**Comment by nickoferrall** [comment]
Conflicts are fixed - I'll merge it now @mattkrick

**Comment by nickoferrall** [comment]
@mattkrick I've fixed the conflicts but the typechecks are failing in files that I haven't touched in this PR. Perhaps it's related to the [GraphQL version change](https://github.com/ParabolInc/parabol/pull/4193/checks)? Strangely, the User Presence [PR](https://github.com/ParabolInc/parabol/pull/4147/checks) fails with the same typecheck errors.

**Comment by ackernaut** [comment]
### Test cycle no. 1
- [x] When a team is archived the templates that the team has shared with the org are also archived
- [x] Existing meetings still point to the archived template

**Review by ackernaut — APPROVED** [review]
Manual tests LGTM

**Pull request merged**
