### PR TITLE
Center control bar

### PR DESCRIPTION
**Pull request by nickoferrall**
PR for issue #4293 

### AC

- [ ]  the meeting bottom bar is centered in the meeting area
- [ ]  dragging the meeting bottom bar on a retro meeting still has the desired effects (columns shrink up when it approaches them)

### Considerations

- To center the control bar correctly for the Estimate stage, I needed to account for the right sidebar drawer so I've branched off of that PR. I suggest that this PR is only reviewed once #4317 is in master
- I've also adjusted the poker deck to account for the right sidebar drawer

### CODE REVIEW

**Comment by mattkrick** [comment]
looks like a couple conflicts. @nickoferrall can you resolve & let @ackernaut know when to review?
Terry, just want your eyes on this to make sure that everything is centered when the left showing/hidden & the deck is centered under the bottom bar

**Comment by nickoferrall** [comment]
sure thing - I've resolved the conflicts. 

@mattkrick I just want to check whether the expectation here is to only center the control bar or center the control bar and the poker deck? In this PR, I've centered the control bar and additionally updated `usePokerDeckLeft` to center the deck on large screens but it's not centered on smaller screens. 

I'd be happy to work on centering the deck too if you like? 

Might be best to hold off on the review Terry until that's clarified

**Comment by ackernaut** [comment]
### Test no. 1
- [ ]  the meeting bottom bar is centered in the meeting area
- [ ]  dragging the meeting bottom bar on a retro meeting still has the desired effects (columns shrink up when it approaches them)

**Review by ackernaut — APPROVED** [review]
Hello, I see that the bar is centered when the view initially loads. And I saw that the columns still resize when dragging the bar.

When I collapse the left navigation, the bar doesn’t move to be in the new center position. Could the layout be updated when that state changes? If the sidebar is opened or closed, the bottom bar updates its position?

**Comment by nickoferrall** [comment]
@ackernaut nice catch! I've pushed an update accounting for the open/closed sidebar

**Comment by ackernaut** [comment]
Nice work on this one 👾

**Pull request merged**
