### PR TITLE
Client no server

### LINKED ISSUE #4467: Remove parabol-server as dependency for parabol-client
codependency is bad. in life & in code.
by removing parabol-server as a client dependency, we should be able to improve build & lint times because processing client tasks won't spread to server things.

AC
- [ ] nothing on the client depends on something that lives in the server package. 
- [ ] if necessary, a shared package is created where we can dump shared assets

Estimate: 16 hours

### PR DESCRIPTION
**Pull request by mattkrick**
fix #4467

What does it do?
- moves all shared assets to the client so parabol-client does not depend on parabol-server
- removes HMR from parabol-server. it was broken.
- adds react-refresh to the client. this should make front-end work go much faster. it preserves local state across refresh so you can change a bunch of stuff & it'll just magically update. the downside is it takes an extra 12 seconds to start up
- moves HMR into its own server. that means the client assets are completely autonomous from the server, which means we should never have to do a full client rebuild after the first one
- moves relay-compiler to pm2. forking it got messy. the process will restart if the schema.graphql file changes
-  moves gql executor & the socket server to PM2. whenever a file in packages/server changes, these servers will restart. they only take 2 seconds to restart!
- moves the socket server to port 3001 for dev. note: add SOCKET_PORT=3001 to the .env!
- adds `yarn update-schema`. whenever you change the server schema, just call this in the terminal. it will update the schema, which will cause the relay-compiler process to restart.

HOW TO UPGRADE:
- add `SOCKET_PORT=3001` to your .env for local development
- `node scripts/dev.js -i` to rebuild the toolbox (just need to call this once)
- then just call `yarn dev` and everything should just work magically.

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut would you like to take this for a test drive? go ahead & change some css or constEnums around & the client should update _really_ fast, without a refresh. the goal is that you'll never have to ctrl+c the server again.

**Comment by ackernaut** [comment]
Hawt dawg! I’m looking at #4453 atm but can get this branch running soon.

**Comment by ackernaut** [comment]
@mattkrick I meant to get back to you sooner. Sorry for the delay. I took the steps above under ‘How to Upgrade’

I saw a spinner in the main timeline view of the dashboard. I tried signing out and back in. I seem to be missing some origin object locally?

```🔥🔥🔥 Ready for Sockets: Port 3001 🔥🔥🔥
💧💧💧 Ready for GraphQL Execution 💧💧💧
ℹ ｢wdm｣: 180 assets
2235 modules
webpack 5.10.3 compiled successfully in 8005 ms
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: wait until bundle finished: /app.js
ℹ ｢wdm｣: 182 assets
2235 modules
webpack 5.10.3 compiled successfully in 1009 ms
ℹ ｢wdm｣: Compiled successfully.
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
ReferenceError: origin is not defined
    at new AuthToken (webpack-internal:///./packages/server/database/types/AuthToken.ts:35:82)
    at setFreshTokenIfNeeded (webpack-internal:///./packages/server/socketHandlers/handleConnect.ts:33:27)
    at handleConnect (webpack-internal:///./packages/server/socketHandlers/handleConnect.ts:54:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async handleOpen (webpack-internal:///./packages/server/socketHandlers/handleOpen.ts:25:25)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
ReferenceError: origin is not defined
    at new AuthToken (webpack-internal:///./packages/server/database/types/AuthToken.ts:35:82)
    at setFreshTokenIfNeeded (webpack-internal:///./packages/server/socketHandlers/handleConnect.ts:33:27)
    at handleConnect (webpack-internal:///./packages/server/socketHandlers/handleConnect.ts:54:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async handleOpen (webpack-internal:///./packages/server/socketHandlers/handleOpen.ts:25:25)
Trace: {
  error: '[{"message":"origin is not defined","locations":[{"line":6,"column":3}],"path":["loginWithGoogle"]}]'
}
    at executeGraphQL (webpack-internal:///./packages/server/graphql/executeGraphQL.ts:85:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Redis.onMessage (webpack-internal:///./packages/gql-executor/gqlExecutor.ts:15:18)
SEND TO SENTRY [Error: origin is not defined] undefined```

**Comment by mattkrick** [comment]
huh, that's really weird why my system didn't bork, that was a pretty valid bug!
should be working now

**Comment by ackernaut** [comment]
> huh, that's really weird why my system didn't bork, that was a pretty valid bug!
> should be working now

Hmm, okay, I’ll take another look. For some reason, I still have weird QA magic, haha.

**Comment by ackernaut** [comment]
So does the `-i` flag only work on `node scripts/dev.js -i` now?
```
parabol git:(client-no-server) yarn dev -i
yarn run v1.22.10
$ node scripts/dev.js && pm2-runtime start pm2.dev.config.js -i
📘 Using cached DLL

  error: option `-i --instances <number>' argument missing

error Command failed with exit code 1.
```

**Comment by ackernaut** [comment]
Good news, I was able to change `BACKGROUND_MAIN` in our palette and it was very quick and painless. 👍  this is gonna help sooo much

**Comment by mattkrick** [comment]
that's correct! all the weirdness in forking was done away with so there's no need to run the -i ever again

**Comment by mattkrick** [comment]
hey @ackernaut any success on getting this working?

**Comment by ackernaut** [comment]
> Good news, I was able to change `BACKGROUND_MAIN` in our palette and it was very quick and painless. 👍 this is gonna help sooo much

Yep ⬆️

**Comment by mattkrick** [comment]
boom! so glad to hear it

**Pull request merged**
