### PR TITLE
Update new meeting illustrations

### PR DESCRIPTION
**Pull request by Dschoordsch**
Resolves: #5484

### CODE REVIEW

**Review by igorlesnenko — APPROVED** [review]
Looks good to me

**Comment by enriquesanchez** [comment]
@Dschoordsch I updated the meeting illustrations because the inconsistency of the bottom line and how it looked on the meeting cards was bothering me a bit.

I removed the line and cleaned up a little the bottom section of all of the illustrations. I also changed them so all of them have a little of overlap at the bottom (the octopus, the microscope, and the plan container). I feel all of them look more consistent now. 

Please let me know what you think.

Before:
Screen Shot 2022-01-11 at 12 59 16 p m

After:
Screen Shot 2022-01-11 at 3 24 39 p m

**Review by enriquesanchez — APPROVED** [review]
From a design stand point, and after the updates to the illustrations, this LGTM 👍

**Comment by Dschoordsch** [comment]
@enriquesanchez Looks good to me for the meeting cards. I just ran the PNGs through tinypng.com again to decrease their size. Did you also check the new meeting dialog?

**Comment by enriquesanchez** [comment]
@Dschoordsch Ah, I ran them through ImgOptim but couldn't get them to a smaller. Will check out tinypng.com next time 👍

>Did you also check the new meeting dialog?

I did and I thought it was fine. Did you find any issues there?

**Comment by mattkrick** [comment]
for posterity-- looks like these had a raster brush applied to them to add extra texture so vectors are out of the question. 
the compression is pretty darn impressive! if we can keep these at 50KB i've got no beef with pngs moving forward. if we get into the 500KB+ range we'll probably want to use resolution specific (ie device-specific) handling. future problem for now. onward!

**Pull request merged**
