### PR TITLE
Fixes template dialog select button

### LINKED ISSUE #4526: 'Use Template' FAB overlaps share button in funky way
## Issue - Enhancement

The 'use template' button overlaps the 'share with...' button right next to it, and the spacing around them looks funky: 
Screen Shot 2021-01-14 at 4 41 11 PM
Screen Shot 2021-01-14 at 4 45 43 PM

Because there's a bit of space to the left of the share button, and the FAB isn't overlapping anything else, I think it looks like an error. 

### Acceptance Criteria (optional)
FAB either doesn't overlap share button, or the overlap looks intentional. 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by ackernaut**
Fixes #4526 

*Note*: upon approval, I’ll wait until `brand-updates` merges to merge this PR

### Tests
- [ ] When the template is not active, all details will scroll out from under the floating action button
- [ ] The sharing menu toggle is minimal, separated by a divider, and is in the scrollable details section

Screen Shot 2021-02-08 at 13 27 13

### CODE REVIEW

**Comment by ackernaut** [comment]
@tianrunhe mind giving a review?

**Comment by tianrunhe** [comment]
There is a horizontal scroll bar but looks like no content overflows?

**Review by tianrunhe — CHANGES_REQUESTED** [review]
Code LGTM

**Comment by ackernaut** [comment]
Good catch @tianrunhe 🦅 

That latest commit should fix that. Thank you!

**Review by tianrunhe — APPROVED** [review]

**Pull request merged**
