### PR TITLE
feat(Team Insights): Add most used retro templates

### LINKED ISSUE #8467: Insights: Top Templates
## Acceptance criteria
* at a regular end of a retro, store the used template and time in `TeamInsights` table
* add GraphQL type and UI

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Fixes #8467 

We accumulate the used templates from the past 1 year of use at the end of a meeting and show them in insights. I've chosen 1 year as there are a lot of teams running retros only once a month, so 30 days like for the other insights is too short of a period.

## Demo

https://www.loom.com/share/495b2ad2232f477d9d68bbff81c219ce?sid=464ce1c3-6f36-4764-8ad7-3570f91e0d97

## Testing scenarios

- enable `teamInsights` org flag
- finish any meeting
- when there was at least 1 retro run in the last year, see top retro templates appear in insights
- run a retro with another template and see it affecting the insight

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

**Review by igorlesnenko — CHANGES_REQUESTED** [review]
emoji insights disappearing after I get retro template insights

Can you see this behaviour?

Before:
Screenshot 2023-09-26 at 14 29 59

After:
Screenshot 2023-09-26 at 14 30 59

**Comment by igorlesnenko** [comment]
Actually looks like I see same favourite reactions on many teams

image

**Comment by igorlesnenko** [comment]
I also see this server logs

```
14:29:22 1|GraphQL Executor  | GEORG engagement undefined
14:30:34 1|GraphQL Executor  | GEORG engagement undefined
14:31:28 1|GraphQL Executor  | GEORG engagement undefined
```

**Comment by Dschoordsch** [comment]
> I also see this server logs
> 
> ```
> 14:29:22 1|GraphQL Executor  | GEORG engagement undefined
> 14:30:34 1|GraphQL Executor  | GEORG engagement undefined
> 14:31:28 1|GraphQL Executor  | GEORG engagement undefined
> ```

This is from the base branch, I'll fix it in that PR.

> emoji insights disappearing after I get retro template insights

This is expected behaviour if you've previously updated the `Team` table manually to see the favourite emojis. At the end of each meeting, the team insights are updated with current data.

**Review by igorlesnenko — APPROVED** [review]

**Pull request merged**
