### PR TITLE
optimise editing of icebreaker + fix flex bug

### LINKED ISSUE #4218: "Icebreaker": Customize text – indicate edit mode
## Usability Enhancement

I clicked on the "customize" icon and expected something like a modal. Your current solution is even better to edit inline – but in fact I only realized that the text is selected. There was no indication that I am in edit mode.

Screen Recording 2020-09-30 at 12 34 21

I think you could indicate more that you are in "edit" mode now.

Screen Recording 2020-09-30 at 12 45 16

- **Estimated effort:** 13 points

### LINKED ISSUE #4219: "Icebreaker" – Change icon to edit text
## Usability - Enhancement

I think the "Customize" icon is a bit over the top – especially as you only can edit the text. I think a simple pen icon would fit better.

image

- **Estimated effort:** 11 points

### LINKED ISSUE #4252: Icebreaker: Prevent jumping "Refresh"-Button
## Issue - Bug

jumping-refresher

When refreshing the Icebreaker several times, the buttons jump horizontally, if the text is too short.

### PR DESCRIPTION
**Pull request by mariohamann**
As requested by @ackernaut I created a PR to close #4219, close #4218 and close #4252 

## Before
before

## After
after

## Comments
- I know, the new CSS in `QuestionBlock` isn't very beautiful. I thought about creating a new `const` extending `EditorInputWrapper` but I wanted to change as less code as possible.
- `isEditing`was used to hide the buttons when editing. I personally don't think that it's needed.
- I renamed `selectAllQuestion` to `focusQuestion` as we don't select the text anymore.
- To prevent the jumping buttons, I had change the `div` in `NewMeetingCheckInPrompt.tsx` to a component having a width of 100%. Furthermore the `.DraftEditor-root` needed `flexGrow: 1`. The text area takes always the full width now – but in my opinion that's fine and makes the editing area a lot clearer, even if the text is very short.
- CSS-Transitions would be beautiful. :)

### CODE REVIEW

**Comment by mariohamann** [comment]
Second commit to close #4211 
Safari seems to behave different in flexbox than e. g., therefore `flexShrink: 0` is needed sometimes.

**Comment by mattkrick** [comment]
oh this is great work. yeah, the weird flex 0 thing has definitely bitten us a time or 2 before.

@ackernaut mind giving this a review?

**Comment by ackernaut** [comment]
Yep, I’ve got a card for it

**Comment by ackernaut** [comment]
Hey @mariohamann I was looking to review this locally but I’m having trouble getting past merge conflicts. Would you be able to merge the latest from `parabolinc:master` and push here?

**Comment by mariohamann** [comment]
Merged master. Does it work? Otherwise I could do some rebasing.

**Comment by ackernaut** [comment]
Yes, that was perfect. It was pretty ugly otherwise.

**Review by ackernaut — APPROVED** [review]

**Comment by ackernaut** [comment]
Nice work @mariohamann and thank you.

**Pull request merged**
