### PR TITLE
ignore quantity changes for enterprise orgs

### LINKED ISSUE #3803: stripe quantity mismatch bug
There are a handful of cases where the quantity billed in stripe don't match up with the quantity of org users. We need to fix this.

Known bugs:
- Removing a paused user reduces the quantity. since a paused user is already not part of the seat count, their removal should not further reduce the count. This results in an undercharge starting at the time of the removal of the paused user. The bug has existed forever. It is coming to light now because the system now verifies quantity after each adjustment & reports an error if there's a mismatch.
- Prior to the atomic stripe fix, some invoice items got combined. This didn't affect seat count, but caused invoice detail lines to be inaccurate (e.g. 2 users paused at the same time would be attributed to a single user)
- When we upgrade someone to enterprise, we give them a set number of seats (e.g. 250). currently, when a user is added or removed, we adjust this number. in hindsight, that's probably not great. We'll fix that by not adjusting the stripe quantity. if they go over, we'll simply log it to segment and sales can do their thing.
- unpaused users show up on the invoice as "paused until X". X was null. this doesn't affect billing, but it might be confusing to see. 

AC
- [ ] when a user is removed, we see if they are inactive. if they are, we do not create an invoice item hook for them
- [ ] when an enterprise account changes quantity, the app doesn't tell stripe about it.

Estimate: 8 hours

### PR DESCRIPTION
**Pull request by mattkrick**
We had a couple bugs with invoices. this fixes those.

fix #3803

TEST
- [ ] create an enterprise organization with 49 seats
- [ ] turn on the ultrahook webhook listener
- [ ] add a user to the enterprise org
- [ ] verify that the quantity in stripe is still 49
- [ ] remove that user & verify that the quantity is still 49
- [ ] create a pro org & invite 1 person
- [ ] put that person on pause & see the pause show up on the upcoming invoice
- [ ] remove the person, verify that the invoice does not change

### CODE REVIEW

**Comment by ackernaut** [comment]
### Test no. 1
- [ ] create an enterprise organization with 49 seats
- [ ] turn on the ultrahook webhook listener
- [ ] add a user to the enterprise org
- [ ] verify that the quantity in stripe is still 49
- [ ] remove that user & verify that the quantity is still 49
- [ ] create a pro org & invite 1 person
- [ ] put that person on pause & see the pause show up on the upcoming invoice
- [ ] remove the person, verify that the invoice does not change

**Comment by ackernaut** [comment]
Should we change the language around removing a member on the enterprise tier, or kick that can down the road?

Screen Shot 2020-05-06 at 12 52 01 PM
Screen Shot 2020-05-06 at 12 52 11 PM

**Comment by ackernaut** [comment]
Almost there! So far I can’t reliably verify that the invoice is changing when pausing or removing a member on the Pro tier. Still troubleshooting.

**Comment by mattkrick** [comment]
> Should we change the language around removing a member on the enterprise tier, or kick that can down the road?

Let's kick it down the road. it's not necessarily wrong, but since the refund amount is $0, it may be misleading

**Pull request merged**
