### PR TITLE
fix: Added automatic docker host platform detection to yarn db:start, db:stop

### PR DESCRIPTION
**Pull request by jordanh**
I got tired of needing to modify dev.yml for my M1 based mac. I changed the dev.yml to accept environment variables that can specify which platform to use, create a script that emits these environment variables, and modified package.json to tie these two elements together.

Tested on M1. It would be good to verify these changes work on an x86 architecture (Linux, OSX, or otherwise)

### M1 architecture machine
- [ ] Run `yarn db:start`, docker-compose starts as expected
- [ ] Run `yarn db:stop`, docker-compose stops as expected

### x86 architecture machine
- [x] Run `yarn db:start`, docker-compose starts as expected
- [x] Run `yarn db:stop`, docker-compose stops as expected

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions

   (Note: I haven't been able to test x86, since I no longer own a machine with this architecture)

- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by BartoszJarocki** [comment]
I'm curious, what kind of problems did you have with running the app? I'm on m1 too and I don't have any issues

**Comment by mattkrick** [comment]
I think we could now safely remove the `platform` arg & it'll select the best architecture for our system (for M1 it'll pick ARM & fallback to AMD)

If memory serves, we added the `platform` arg back when M1s just came out & docker didn't play ball

**Comment by jordanh** [comment]
> I think we could now safely remove the platform arg & it'll select the best architecture for our system (for M1 it'll pick ARM & fallback to AMD)

Oh interesting, that's worth trying.

I made this PR because I couldn't start the app with the wrong platform specified. I found [this Slack thread](https://parabol.slack.com/archives/C836NA350/p1654699847781779) and wanted to make the world a better place

Let me test removing it and seeing what happens

**Comment by jordanh** [comment]
@mattkrick so, without the `PLATFORM` it works fine. I inspected the containers docker selects and they are correct.

Only one small nit: you get a warning on redis-commander because no platform is specified (redis-commander has no arm64 image).

```
 ⠿ Network docker_parabol-network                                                                                                                                 Created                                                   0.0s
 ⠿ Container docker-db-1                                                                                                                                          Started                                                   0.6s
 ⠿ Container redis_commander                                                                                                                                      Started                                                   0.6s
 ⠿ Container docker-redis-1                                                                                                                                       Started                                                   0.6s
 ⠿ Container docker-postgres-1                                                                                                                                    Started                                                   0.6s
 ⠇ redis-commander The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                           0.0s
 ⠿ Container pgadmin_container                                                                                                                                    Started                                                   0.8s
✨  Done in 1.22s.
```

If we want no warnings, we should hardcode the PLATFORM for Redis Commander and add a comment. I will revise this PR with that change.

**Comment by jordanh** [comment]
@mattkrick ok, much simpler now. If you're comfortable with this, please merge it

**Comment by jordanh** [comment]
@BartoszJarocki I couldn't start `yarn dev` on my system without removing the redis platform hardcoding. I got this error:

```
Error response from daemon: image with reference redis:latest was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8
```

**Comment by BartoszJarocki** [comment]
Interesting! are you on the newest docker version? I'm curious why it works on some machines

**Comment by mattkrick** [comment]
I think your shell script is now an orphan?

redis-commander has a new home now & it supports M1s natively. i'll add a PR for your consideration

**Comment by mattkrick** [comment]
for your consideration: #7786

**Comment by jordanh** [comment]
@mattkrick merge it!

**Pull request closed without merging**
