### PR TITLE
fix: Reset retro meeting to group stage response handling

### LINKED ISSUE #5383: payload can be null in ResetRetroMeetingToGroupStageMutation
Affected 9 users in the past 16 days since v6.24.1

https://sentry.io/organizations/parabol/issues/2607259830/?referrer=github_plugin

```
TypeError: Cannot read properties of null (reading 'getLinkedRecords')
  at resetRetroMeetingToGroupStageUpdater (./packages/client/mutations/ResetRetroMeetingToGroupStageMutation.ts:52:43)
  at updater (./packages/client/mutations/ResetRetroMeetingToGroupStageMutation.ts:73:7)
  at Set.forEach (<anonymous>)
  at updateIsEditing (./packages/client/components/ReflectionCard/ReflectionCard.tsx:110:5)
  at g (./packages/client/components/ReflectionCard/ReflectionCard.tsx:121:18)
...
(15 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by shapel**
Fix #5383

### CODE REVIEW

**Comment by shapel** [comment]
👋 @mattkrick do you have a chance to review or assign someone to do this?

**Comment by mattkrick** [comment]
Any steps to reproduce? The early return _might_ fix it, but i'm not sure why it'd be undefined in the first place 🤷

**Comment by shapel** [comment]
@mattkrick  Do we need to go deeper into the root cause before merging this little fix?

**Comment by shapel** [comment]
👋 @mattkrick hope 👆 on your radar...

**Comment by shapel** [comment]
👋 @mattkrick hope 👆 on your radar...

**Comment by mattkrick** [comment]
LGTM! sorry for the delay!

**Pull request merged**
