### PR TITLE
fix: deleting team prevents reuse of deleted team's name

### LINKED ISSUE #6484: Bug: deleting team prevents reuse of deleted team's name
Steps to Reproduce:

1. Create a new team with name, 'X'
2. Delete team 'X'
3. Notice the notification in the red box that 'X' has been archived.
4. Create another new with same name, 'X'
5. Notice the bug

See video:

https://user-images.githubusercontent.com/35351786/166073866-44579273-4b96-4aa6-b53f-6a53552f93b3.mp4

Note: Not seen in the clip at the end, but after entering the name and being presented with the prompt, user cannot move forward and create the team.

## Acceptance criteria
* [ ] duplicate team name check only considers teams that are not deleted/archived

### PR DESCRIPTION
**Pull request by gitstart**
# deleting team prevents reuse of deleted team's name
User cannot create a team with the same **team name** if **team name**  if **team name** has ever been used and deleted
Fixes/Partially Fixes #6484

## Demo
https://www.loom.com/share/263bf037561244d8ad55edd75a45cbee
## Testing scenarios

- [ ] Scenario A
  - Create a new team with name, 'X'
  - Delete team 'X'
  - Notice the notification in the red box that 'X' has been archived.
  - Create another new with same name, 'X'

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by gitstart-parabol** [comment]
@jmtaber129 this PR is ready for review

**Comment by Dschoordsch** [comment]
@igorlesnenko James is out, can you do the review?

**Review by igorlesnenko — CHANGES_REQUESTED** [review]
With this change, we now only run validation on new organizations that don't have any teams anyway.

And we don't run validation on existing organizations with existing teams at all. However, validation is still needed here.

We only want to exclude teams that have been archived from validation. We need to filter teams ideally at the API level or here: `teamNames = org.teams.map((team) => team.name)` 

Additionally, I see we didn't decide if we need that change and I see the issue iceboxed and closed, see: https://github.com/ParabolInc/parabol/issues/6484#issuecomment-1122719509

@jordanh We decided not to make this change?

**Comment by Dschoordsch** [comment]
I decided we still want to have this change. I've updated the issue and clarified the acceptance criteria.

**Comment by gitstart-parabol** [comment]
@igorlesnenko we have amended the implementation to meet the acceptance criteria properly, please take a look.

**Review by igorlesnenko — CHANGES_REQUESTED** [review]
While testing this issue, I just noticed one thing — there is no actual restriction on using the name of the deleted team. If you refresh the page, you will be able to successfully pass the validation.

That means, API does not actually return `archived` teams.

I think, the right way to fix this is to fix updaters of `ArchiveTeamMutation`.

And this also means that this is a pretty rare case — without refreshing the page, a user needs to load the team creation screen for any reason, then, delete a team, then create a team with the same name.

cc @Dschoordsch

**Comment by gitstart** [comment]
> While testing this issue, I just noticed one thing — there is no actual restriction on using the name of the deleted team. If you refresh the page, you will be able to successfully pass the validation.
> 
> That means, API does not actually return `archived` teams.
> 
> I think, the right way to fix this is to fix updaters of `ArchiveTeamMutation`.
> 
> And this also means that this is a pretty rare case — without refreshing the page, a user needs to load the team creation screen for any reason, then, delete a team, then create a team with the same name.
> 
> cc @Dschoordsch

@igorlesnenko, This comment aided in determining the ideal fix to the bug. you can please double check once again.

**Comment by gitstart-parabol** [comment]
> While testing this issue, I just noticed one thing — there is no actual restriction on using the name of the deleted team. If you refresh the page, you will be able to successfully pass the validation.
> 
> That means, API does not actually return `archived` teams.
> 
> I think, the right way to fix this is to fix updaters of `ArchiveTeamMutation`.
> 
> And this also means that this is a pretty rare case — without refreshing the page, a user needs to load the team creation screen for any reason, then, delete a team, then create a team with the same name.
> 
> cc @Dschoordsch

@igorlesnenko, This comment aided in determining the ideal fix to the bug. you can please double check once again.

**Review by igorlesnenko — APPROVED** [review]

**Review by Dschoordsch — APPROVED** [review]
Tested, works. Good job!

**Pull request merged**
