### PR TITLE
Ended meetings

### LINKED ISSUE #3680: Make ended meetings easy to re-enter
@ackernaut 

i'll be building this out today, please comment/edit the AC as you see fit

AC
- [x] Phase completed banner added per #3421
- [x] reflect phase shows all reflections even after grouping (if not too hard)
- [ ] timeline artifacts point to the meeting, not the summary
- [ ] goto summary link added in left nav (if meeting not killed)
- [x] meeting completed tag added in top left

Effort: 11 points

### PR DESCRIPTION
**Pull request by mattkrick**
This allows folks to go back into meetings to view discussions. fix #3680

TEST
- [ ] after a stage is complete it says "Stage Completed"
- [ ] after a meeting is completed, it says "Meeting Completed" in the left nav header
- [ ] can go back to the reflect phase & see the reflections that you wrote
- [ ] can go to the timeline view & see extra meeting stats, including # of comments
- [ ] from the timeline event can go back into an old meeting to see the discussion

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready for review

**Comment by ackernaut** [comment]
### Test cycle no. 1
- [ ] after a stage is complete it says "Stage Completed"
- [ ] after a meeting is completed, it says "Meeting Completed" in the left nav header
- [ ] can go back to the reflect phase & see the reflections that you wrote
- [ ] can go to the timeline view & see extra meeting stats, including # of comments
- [ ] from the timeline event can go back into an old meeting to see the discussion

**Comment by ackernaut** [comment]
I have some notes to add (still reviewing), but also we could consider knocking out:
>Summary has links to individual topics #3687

**Comment by ackernaut** [comment]
A few notes re: stage completed:

- I see that it says stage but maybe we should consider going by phase to support navigating back and forth without feeling like that stage is finished when a phase has many stages. The intent for the badge was when the meeting was completed, otherwise I hadn’t thought through these nuances that I’m noting.

- I think we shouldn’t apply the label to the Reflect phase until the Vote phase is started.

- I think we shouldn’t apply the label to the Discuss phase until the meeting is over. If the facilitator jumps around in an async meeting (or even a sync meeting) it may look like that discussion is closed intentionally when it’s not. (I’d even consider leaving it off the Discuss phase entirely since the discussion can continue, but that’s antithetical to having a completed meeting UX.)

**Comment by mattkrick** [comment]
fixups

- [ ] change stage completed to phase completed

**Pull request merged**
