### PR TITLE
fix: only query templates when a user clicks the options menu

### PR DESCRIPTION
**Pull request by nickoferrall**
Fix https://github.com/ParabolInc/parabol/issues/9620

### To test

- [ ] Load a retro meeting and see that the templates are not queried by default
- [ ] Click on the options menu in the Reflect stage and see that the templates are now queried

### CODE REVIEW

**Comment by nickoferrall** [comment]
Hey @mattkrick, could you review this one please?

**Comment by mattkrick** [comment]
Doesn't seem to work, video included to show how i tested: https://www.loom.com/share/fc18f08c50c441ee88e18f20ff99e154?sid=1bd925dc-3e67-4a14-926c-57391a23c502

**Review by mattkrick — CHANGES_REQUESTED** [review]
still fires the query before opening

**Comment by nickoferrall** [comment]
Thanks @mattkrick. That should be fixed now. Here's a quick Loom demo with the update: https://www.loom.com/share/1d448ddf057e40f29ff5e4e1eb211eef

**Comment by mattkrick** [comment]
lookin good!

**Review by mattkrick — APPROVED** [review]

**Pull request merged**
