### PR TITLE
Workaround for null reflections in GroupingKanban

### PR DESCRIPTION
**Pull request by Dschoordsch**
There is nothing obvious causing this issue and I couldn't reproduce it. Handle the error for now so the client is not affected but still track the error in Sentry so we can eventually find the root cause.

Resolves: #5902

### CODE REVIEW

**Comment by Dschoordsch** [comment]
@nickoferrall could you please take a look?

**Review by nickoferrall — APPROVED** [review]
LGTM 👍

**Comment by mattkrick** [comment]
man, this bug has stumped me for literally years... 
We also catch it here: https://github.com/ParabolInc/parabol/blob/213890d97e38bdb32f7fac045373f3b2ee212965/packages/client/components/RetroDiscussPhase.tsx

This PR is safe & definitely an improvement.
I think the next step is to figure out if this is caused by an optimistic updater function. If so, we know where to look. If not, we need to see if this affects the person calling the mutation, or if it happens to subscribers who receive the payload, too.

**Comment by mattkrick** [comment]
Next issue here: https://github.com/ParabolInc/parabol/issues/6055

**Pull request merged**
