### PR TITLE
Fix long meeting names throwing off meetings view

### PR DESCRIPTION
**Pull request by nickoferrall**
PR to resolve issue #5107 

I also noticed that long words can overflow on the meeting card and in the meeting. See screenshots:

long-name-1

long-name-2

### AC:

- [ ] if the meeting name or team name takes up multiple lines or if there's a user in the meeting, the rows below that meeting card adjust their position accordingly
- [ ] long meeting or team names don't overflow on the card or in the meeting

Would be interested to get your thoughts on the design @enriquesanchez

### CODE REVIEW

**Comment by enriquesanchez** [comment]
Screen Shot 2021-07-09 at 3 23 15 p m

@nickoferrall The long names issue looks fixed on my end, but I think I am missing a step or something for testing this PR because the layout is still broken

**Comment by nickoferrall** [comment]
@enriquesanchez huh that's strange - I just checked out the branch, ran a `yarn` and `yarn dev` but the layout is working on my end on Chrome & Safari. Mind trying again and, if you get the same result, we could Zoom together to reproduce it?

**Comment by enriquesanchez** [comment]
@nickoferrall Ah, I forgot to run `yarn dev`... again 🤦‍♂️
Sorry about that. Here's a screen grab on Firefox:

Screen Shot 2021-07-12 at 12 19 52 p m

👍 It looks good!

Did you also work on adding the text "No one has joined" ?

**Comment by nickoferrall** [comment]
Ahh that's good to hear! I haven't added the "No one has joined" text yet. I think it's a helpful way of keeping the meeting cards the same height when displaying the avatar list but I also kinda like that active meetings are larger and draw the user's attention. Plus the card heights will be different anyway if there's a long meeting / team name.

Do you have any strong opinions on this one?

**Comment by enriquesanchez** [comment]
>Do you have any strong opinions on this one?

@nickoferrall No strong opinions, you're are right it doesn't fully solve the issue.

**Review by enriquesanchez — APPROVED** [review]

**Comment by mattkrick** [comment]
you did it! this PR brings back some feels. many years ago our retrospectives used a masonry grid instead of the columns we have today. i had to use many of the complicated patterns that this PR uses, like the variable length array of refs. eventually, the logic got to be too complex. For this case, I'd ask what happens if a meeting gets renamed to be really long? or short? or everyone leaves the meeting? or 2 meetings get created during the same render cycle? or 1 meeting ends & 1 gets created in the same render cycle?)

we're sacrificing a simple DX for animations, and if that's the price we pay, so be it because animations are awesome. buuuuut, i still gotta wonder if we can make it simpler. for example, https://github.com/ParabolInc/parabol/blob/f092a703bd675aaaa5129d3e155c6d4cb51474e2/packages/client/modules/teamDashboard/components/TeamArchive/TeamArchive.tsx uses react-virtualized which accomplishes the same thing. basically, they give you a `cellCache` and whenever something _could_ change the height, then you call `cellCache.clearAll()` and it recalcs everything. 

i'll spend an hour or 2 tonight to see if we can simplify the pattern. if not, LGTM! truly a great feat of engineering & really well done

**Comment by mattkrick** [comment]
LGTM! If you're ready to merge, merge away!

**Pull request merged**
