### PR TITLE
trigger confirm on next

### PR DESCRIPTION
**Pull request by mattkrick**
TEST
- [ ] start a meeting, have a participant in a 2nd browser
- [ ] as participant, click "ready", the facilitator can progress the meeting as normal
- [ ] when the participant is not ready & the facilitator clicks next, they must click next again within 3 seconds to confirm
- [ ] to end the meeting, the facilitator must click end meeting 2x in 3 seconds
- [ ] the facilitator cannot advance to the next phase by clicking the phase in the left nav

Ready feature
- [ ] as a participant, the checkmark is gray if you're not ready, it's green if you are

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready for review!

**Comment by mattkrick** [comment]
@ackernaut i think this would be a good client-facing feature to get into the ship for tomorrow.

**Comment by ackernaut** [comment]
### Test cycle no. 1
- [ ] start a meeting, have a participant in a 2nd browser
- [ ] as participant, click "ready", the facilitator can progress the meeting as normal
- [ ] when the participant is not ready & the facilitator clicks next, they must click next again within 3 seconds to confirm
- [ ] to end the meeting, the facilitator must click end meeting 2x in 3 seconds
- [ ] the facilitator cannot advance to the next phase by clicking the phase in the left nav

Ready feature
- [ ] as a participant, the checkmark is gray if you're not ready, it's green if you are

**Comment by ackernaut** [comment]
This is looking good, all the tests worked. A few small details to comment on:
- It feels strange to have to confirm in the Social Check-In. Maybe because I’ve stared at this UX for a long time, and maybe because there’s nothing in the UI blocking forward progress (i.e. nobody clicks ready, there are no inputs from users)
- It’s weird to tap confirm, move to the next stage, but still see the confirm animation winding down
- It also felt a little weird confirming between stages (in the case Discuss topics, but it would be similar for Team Agenda topics). Maybe this is because it’s not a one-way move (folks can go back and form between topic stages). The Retro phases Reflect, Group, and Vote are the one-way moves because input becomes read-only once completed. And of course, ending the meeting.
- I would like to see a neutral gray for both the ready and the next controls. The ring is the hot color for the facilitator. The ring is blue for the participants. When the participant has marked themselves as being ready, the check is blue. When all are ready, the next arrow is the pink for the facilitator.

I’m merging because good even over perfect. I’ll probably open an issue about some bottom bar polish eventually, but letting it simmer.

**Pull request merged**
