### PR TITLE
feat: scroll to card section

### PR DESCRIPTION
**Pull request by nickoferrall**
Fix https://github.com/ParabolInc/parabol/issues/8773

Demo: https://www.loom.com/share/6cbec0355c054008bf4ef9170cd64565?sid=70440557-d590-4921-a07f-5787dd875fd7

### To test

- [ ] Click "Select Plan" in the new checkout flow and see that the page automatically scrolls to the card payment section

### CODE REVIEW

**Review by Dschoordsch — CHANGES_REQUESTED** [review]
https://www.loom.com/share/ea245c17a4334675a632b4bd9cec2fda?sid=9499127b-5fff-4118-90f2-866e1804cb99
Because the cards have all the visuals of a big button, they should behave like one.

**Review by Dschoordsch — CHANGES_REQUESTED** [review]
I'm sorry, I tried the current version and it feels unnatural as well. I don't know how to resolve this and propose we get some feedback from a designer.
@acressall I had some tension around the card appearing to be clickable, see loom above, and suggested to make it actually clickable, but that appears a bit weird to me in practice.
https://www.loom.com/share/a66066ec4b0d484190a82f00c18c4734?sid=45e02633-b67e-4237-8c03-1db8648819b9

I suggest undoing the card button change I had requested and just merge the scroll behaviour and fix the button behaviour separately.

**Comment by acressall** [comment]
> I suggest undoing the card button change I had requested and just merge the scroll behaviour and fix the button behaviour separately.

I agree with @Dschoordsch, we can remove the cursor hover on the card (only have it on the button) for now

**Comment by nickoferrall** [comment]
Cool, here's a Loom with the update: https://www.loom.com/share/d54ca92318924a4f86464f4adfe7c8d3

**Review by acressall — APPROVED** [review]

**Comment by nickoferrall** [comment]
This was largely a design concern, so I'll merge the PR @Dschoordsch now that Alicia's approved it, but let me know if there's anything you'd like changed in the final version

**Pull request merged**
