### PR TITLE
chore: use SDL for JiraIssue

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Relates-To: #7206

Part 2/3

Refactor JiraIssue in SDL first to modify the fields in next PR

## Demo

No demo, everything should behave as always.

## Testing scenarios

- [ ] Run a Sprint poker and play around with Jira issues
- [ ] Push tasks to Jira

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by nickoferrall** [comment]
Hey @Dschoordsch, are there any testing steps for this one?

**Comment by nickoferrall** [comment]
I'm away for Wellness Day tomorrow, so I won't be able to review this PR within 24 hours. @igorlesnenko do you mind if I tag you in to review this PR? If you don't get to it tomorrow, I'd be happy to take it back on Monday 🙏

**Comment by Dschoordsch** [comment]
Nothing should have changed, so just smoke testing Jira issues should be sufficient.

**Review by nickoferrall — COMMENTED** [review]
I haven't spent much time digging into the code, but I tested it out and noticed an "Unknown Story" would optimistically show up when proceeding to the Estimate phase. Not a big deal, but sharing it here to see if you can reproduce it: https://www.loom.com/share/783114f3d4a74fa7998426d1283c94d2

**Comment by igorlesnenko** [comment]
@Dschoordsch for some reason I can't add any Jira issue to the scope

> 15:32:15 1|GraphQL Executor  | error: relation "JiraDimensionFieldMap" does not exist

https://user-images.githubusercontent.com/466991/195837092-5c99f7bc-6d6b-4239-9a0a-b774565a93f2.mov

And after the first attempt, if I refresh the page, meeting becomes broken, I always see Invitation required screen:

image

Am I missing something?

**Comment by Dschoordsch** [comment]
@igorlesnenko did you rebase the changeset? It's not targeting master, but requires #7257 as base.

**Comment by igorlesnenko** [comment]
@Dschoordsch the problem is that for some reason the `JiraDimensionFieldMap` migration didn't run. And I don't see any error running `yarn dev`.

I tried to execute queries manually

With the created table all works fine.

However I'm getting this when trying to populate it:

```
INSERT INTO "JiraDimensionFieldMap" ("teamId", "cloudId", "projectKey", "issueType", "dimensionName", "fieldId", "fieldName", "fieldType")
                          SELECT "Team"."id", jdf->>'cloudId', jdf->>'projectKey', '', jdf->>'dimensionName', jdf->>'fieldId', jdf->>'fieldName', jdf->>'fieldType'
                          FROM "Team", unnest("jiraDimensionFields") as jdf WHERE "jiraDimensionFields" != '{}'
[2022-10-14 18:22:21] [23505] ERROR: duplicate key value violates unique constraint "JiraDimensionFieldMap_pkey"
[2022-10-14 18:22:21] Detail: Key ("teamId", "cloudId", "projectKey", "issueType", "dimensionName")=(2eNhkZkERr, 5f28bfc0-292d-47f2-8d24-9ff14ac1447f, EN, , Story Points) already exists.
```

Do you have any thought about it?

**Comment by Dschoordsch** [comment]
@igorlesnenko I would not try to manually run the migration code or populate the table. Instead you can run migrations with `yarn pg:migrate` and this should hopefully show what's wrong.

The error you're seeing could be from duplicate entries in the json field since it wasn't normalized. I will check on staging if that's a problem which would occur on production as well.

**Comment by Dschoordsch** [comment]
I checked this on staging and it happens there as well. It seems the "jiraDimensionFields" field is inconsistent. Nice find!
For now I would change it to
```
  INSERT INTO "JiraDimensionFieldMap" ("teamId", "cloudId", "projectKey", "issueType", "dimensionName", "fieldId", "fieldName", "fieldType")
    SELECT "Team"."id", jdf->>'cloudId', jdf->>'projectKey', '', jdf->>'dimensionName', jdf->>'fieldId', jdf->>'fieldName', jdf->>'fieldType'
    FROM "Team", unnest("jiraDimensionFields") as jdf WHERE "jiraDimensionFields" != '{}'
	ON CONFLICT ("teamId", "cloudId", "projectKey", "issueType", "dimensionName") DO NOTHING;
```
I will check a bit more what these duplicates are.

**Comment by Dschoordsch** [comment]
I checked the last backup on staging and we have like a dozen cases where we have exact duplicates in the "jiraDimensionFields" field.

**Comment by Dschoordsch** [comment]
> @Dschoordsch When I running `yarn pg:migrate up` I'm getting the following error
> 
> ```
> Error: Not run migration 1648135135375_addAzureDevOpsIntegrationProvider is preceding already run migration 1649750150687_GitLabDimensionFieldMap
> ```
> 
> Should we fix that by renaming migrations?

I have a similar, but different error:
```
Error: Not run migration 1656389795923_addAzureDevOpsDimensionFieldMapWorkItemType is preceding already run migration 1651098260151_OrganizationApprovedDomains
```
This is just a result of running dev branches locally without doing the proper down migration afterwards. I just run it with `--no-check-order` locally, but I guess you could also fix up your local pgMigrations table.

**Review by igorlesnenko — APPROVED** [review]
This PR looks good to me. Having some issues with migrations which is actually related to the previous PR #7257

**Comment by igorlesnenko** [comment]
@Dschoordsch thanks `--no-check-order` works. The issue the same as I mentioned above
Not sure why It do not attempt to run while `yarn dev`

```
> Migrating files:
> - 1663850062796_JiraDimensionFieldMap
> Rolling back attempted migration ...
error: duplicate key value violates unique constraint "JiraDimensionFieldMap_pkey"
```

**Comment by Dschoordsch** [comment]
I modified the migration in the base branch to ignore the duplicate and move on.

**Comment by Dschoordsch** [comment]
Typecheck is failing because of an issue on master. Will merge and investigate separately.

**Pull request merged**
