### PR TITLE
Logos, 2nd pass

### LINKED ISSUE #4729: Logo updates, 2nd pass
In the first pass we wanted to get the new logo and type mark in. In this pass we can get the new color usage in.

### AC
- [x] Auth page (styles SVG)
- [x] Dashboard header (styles SVG)
- [x] Meeting navigation sidebar (styles SVG)
- [x] Basic email header (email-header-branding-color variants, static and S3)
- [x] Summary email header (mark-color at 3x.png, static, S3)
- [x] Summary email footer (mark-color at 3x.png, static, S3)
- [x] Favicon (.png and .ico, static and on S3)
- [x] Apple touch icon (static, S3)
- [x] Web app manifest icons (192x192, 512x512 files updated on S3)
- [x] Invoice footer (static, S3)
- [x] Poker cards (white mark, static, S3)
- [x] GraphQL Admin header (lockup with dark text, SVG)
- Note: the spinner was updated to use the new vector shapes, and takes any color as a prop

### Estimated effort
- 3 hours

### PR DESCRIPTION
**Pull request by ackernaut**
Fixes #4729

### Tests
- [x] Auth page (styles SVG)
- [x] Dashboard header (styles SVG)
- [x] Meeting navigation sidebar (styles SVG)
- [x] Basic email header (email-header-branding-color variants, static and S3)
- [x] Summary email header (mark-color at 3x.png, static, S3)
- [x] Summary email footer (mark-color at 3x.png, static, S3)
- [x] Favicon (.png and .ico, static and on S3)
- [x] Apple touch icon (static, S3)
- [x] Web app manifest icons (192x192, 512x512 files updated on S3)
- [x] Invoice footer (static, S3)
- [x] Poker cards (white mark, static, S3)
- [x] GraphQL Admin header (lockup with dark text, SVG)
- Note: the spinner was updated to use the new vector shapes, and takes any color as a prop

### CODE REVIEW

**Comment by ackernaut** [comment]
I’m still wrangling a quirky SVG canvas…stand by

**Comment by ackernaut** [comment]
Note: some of these changes are live by virtue of being updated on S3. Others become live once we merge and ship.

**Comment by ackernaut** [comment]
@tianrunhe would you give this a review when you get a moment?

**Comment by tianrunhe** [comment]
### Tests
- [ ] Auth page (styles SVG)
- [ ] Dashboard header (styles SVG)
- [ ] Meeting navigation sidebar (styles SVG)
- [ ] Basic email header (email-header-branding-color variants, static and S3)
- [ ] Summary email header (mark-color at 3x.png, static, S3)
- [ ] Summary email footer (mark-color at 3x.png, static, S3)
- [ ] Favicon (.png and .ico, static and on S3)
- [ ] Apple touch icon (static, S3)
- [ ] Web app manifest icons (192x192, 512x512 files updated on S3)
- [ ] Invoice footer (static, S3)
- [ ] Poker cards (white mark, static, S3)
- [ ] GraphQL Admin header (lockup with dark text, SVG)

**Comment by tianrunhe** [comment]
@ackernaut LGTM! Not sure if this is out-of-scope: what about the 404 page?😛

**Review by tianrunhe — APPROVED** [review]

**Pull request merged**
