### PR TITLE
Fix team invitation

### PR DESCRIPTION
**Pull request by nickoferrall**
PR to resolve issue #4744 

Current problems:

1. If a user tries to join a team, the team members in that team may see a React Hooks error.
2. The `team` and `meeting` queries in `ViewerNotOnTeam` are invalid as `teamId` and `meetingId` can be null.

Solutions:

1. This is being caused by `PushInvitationMutation` breaking the rules of hooks which explains why the bug only happens in development and not production.
2. A bug in the Relay compiler prevented it from detecting the error (if we use a regular query instead of a fragment, it does detect the error). It looks like we don't need to check whether `team` or `meeting` exist in `ViewerNotOnTeam` as [MeetingSelector](https://github.com/ParabolInc/parabol/blob/235b57d1790f74b6170f8c3ebd5acf30839a472c/packages/client/components/MeetingSelector.tsx#L34) and [TeamContainer](https://github.com/ParabolInc/parabol/blob/f9693de81dd203521b9d1862b744c186936d636c/packages/client/modules/teamDashboard/containers/Team/TeamContainer.tsx#L34) already do this for us. If they don't exist, the viewer will be sent back to `ViewerNotOnTeam`.

### AC

- [ ] If a user tries to join a team, the team members of that team don't see an error in development
- [ ] If a user tries to join a team, the server doesn't complain that the query is invalid
- [ ] A user can successfully join a team by going to `/team`, an active meeting or using the invitation link

### CODE REVIEW

**Comment by tianrunhe** [comment]
@nickoferrall @mattkrick I've found a failed test case here:

1. User A is in his/her own team A. User B is **not** in team A yet.
2. User A starts a meeting
3. User A copies the meeting URL, e.g., `http://localhost:3000/meet/2IOQ0SeiAg/reflect` and gives to user B
4. User B opens that URL and sees an error, where he/she should have seen the invitation required screen

Stack trace from server looks like:
```
Trace: { error: '{"errors":[{}]}' }
    at executeGraphQL (webpack-internal:///./packages/server/graphql/executeGraphQL.ts:96:13)
    at Redis.onMessage (webpack-internal:///./packages/gql-executor/gqlExecutor.ts:23:26)
    at Redis.emit (events.js:314:20)
    at Redis.EventEmitter.emit (domain.js:486:12)
    at DataHandler.handleSubscriberReply (/Users/brucetian/Projects/parabol/node_modules/ioredis/built/DataHandler.js:80:32)
    at DataHandler.returnReply (/Users/brucetian/Projects/parabol/node_modules/ioredis/built/DataHandler.js:47:18)
    at JavascriptRedisParser.returnReply (/Users/brucetian/Projects/parabol/node_modules/ioredis/built/DataHandler.js:21:22)
    at JavascriptRedisParser.execute (/Users/brucetian/Projects/parabol/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/Users/brucetian/Projects/parabol/node_modules/ioredis/built/DataHandler.js:25:20)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:283:9)
    at Socket.Readable.push (_stream_readable.js:222:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
SEND TO SENTRY [Error] undefined
```

**Comment by mattkrick** [comment]
nice find @tianrunhe! looks like you two have this covered, i'll let you guys poke around some edge cases (hint: search for `/invitation-required` and make sure to trigger each code path that calls that redirect)

**Comment by tianrunhe** [comment]
NVM @nickoferrall it's working. My local has caching issue.

**Comment by tianrunhe** [comment]
Here's a new one.

1. User A is in his/her own team A. User B is **not** in team A yet.
2. User B opens the team page for team A, e.g., http://localhost:3000/team/-iVFYQM4m
3. User B sees the invitation screen and user A sees the invitation snack bar pop up. Everything looks good except error from server:

```
SEND TO SENTRY Error: Not on team
    at Object.resolve [as UserteamMemberResolver] (webpack-internal:///./packages/server/graphql/types/User.ts:471:74)
    at viewerQueryviewerResolverHandler (eval at compileQuery (/Users/brucetian/Projects/parabol/node_modules/graphql-jit/dist/execution.js:69:56), <anonymous>:2919:39)
    at __value.then.__context.errors.push.__context.GraphQLError.line (eval at compileQuery (/Users/brucetian/Projects/parabol/node_modules/graphql-jit/dist/execution.js:69:56), <anonymous>:34:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) undefined
SEND TO SENTRY Error: Team not found
    at Object.resolve [as TeamtasksResolver] (webpack-internal:///./packages/server/graphql/types/Team.ts:286:23)
    at teamUserteamResolverHandler (eval at compileQuery (/Users/brucetian/Projects/parabol/node_modules/graphql-jit/dist/execution.js:69:56), <anonymous>:2619:39)
    at __value.then.__context.errors.push.__context.GraphQLError.line (eval at compileQuery (/Users/brucetian/Projects/parabol/node_modules/graphql-jit/dist/execution.js:69:56), <anonymous>:2861:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {"teamId":"-iVFYQM4m"}
Trace: {
  error: '{"data":{"viewer":{"team":null,"teamMember":null,"id":"google-oauth2|114151680678363045861"}},"errors":[{"message":"Cannot return null for non-nullable field Team.(agendaItems,agendaItems).","locations":[{"line":36,"column":3},{"line":54,"column":3}],"path":["viewer","team","agendaItems"]}]}'
}
    at executeGraphQL (webpack-internal:///./packages/server/graphql/executeGraphQL.ts:96:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Redis.onMessage (webpack-internal:///./packages/gql-executor/gqlExecutor.ts:23:20)
SEND TO SENTRY [Error: Cannot return null for non-nullable field Team.(agendaItems,agendaItems).] undefined
```

@nickoferrall Let me know if you can reproduce this one or it's something wrong again with my local setup...

**Comment by nickoferrall** [comment]
Hmm I haven't been able to repro this one yet. I used an existing team and created a new team and org but didn't get the server error. If it persists for you, I'll see if there's some funky caching going on on my end!

**Comment by tianrunhe** [comment]
Here's a video:

https://www.loom.com/share/5dad6a2654834b26ba18e35f5c6e4fec

**Comment by nickoferrall** [comment]
Still no luck reproducing this one unfortunately. I've followed the steps of inviting a user to a team they're **not** on but I don't get the server error message. 

I've tried creating new users, new teams, leaving a team and rejoining, joining a meeting, re-running `yarn && yarn dev`, restarting my computer... but no joy! Do you think it could be a local set-up issue? Do you still get the same error when using different users?

**Comment by tianrunhe** [comment]
> Still no luck reproducing this one unfortunately. I've followed the steps of inviting a user to a team they're **not** on but I don't get the server error message.
> 
> I've tried creating new users, new teams, leaving a team and rejoining, joining a meeting, re-running `yarn && yarn dev`, restarting my computer... but no joy! Do you think it could be a local set-up issue? Do you still get the same error when using different users?
> 
> If it persists for you, I could ask Matt if he can reproduce it so we can identify which computer is behaving strangely.

I tried two different users and did not see the error anymore🤷‍♂️. Sorry about wasting your time!

**Review by tianrunhe — APPROVED** [review]

**Comment by nickoferrall** [comment]
All good, Sir! Thanks for reviewing it.

Requesting @mattkrick for the final review

**Comment by mattkrick** [comment]
Gonna blabber on while I review this one because there are so many different code paths here.
This PR is great because it simplifies the query-- it removes a check to see if there is a valid meeting or team when someone lands on the ViewerNotOnTeam page.

Lets check the code paths. How does someone end up on /invitation-required?
 - MeetingSelector will send them there if meeting is null, which can happen if the meetingId is invalid or the viewer is not on the team that owns the meeting
- useInitialSafeRoute will send them here if meeting is undefined. This hook is used by `useMeeting` which is used by the 3 different meeting types, which are all children of MeetingSelector. So, this code path _should_ be unreachable due to https://github.com/ParabolInc/parabol/blob/235b57d1790f74b6170f8c3ebd5acf30839a472c/packages/client/components/MeetingSelector.tsx#L58
- TeamContainer will call this if viewer.team is falsy. That's possible if the teamId is invalid or the viewer is not on the team.
- used by inviteToTeamNotificationOnNext. if an invitee gets an invitation & they are on the route, then it automatically accepts the invitation for them & if it was a meeting invitation, they go redirected to the meeting

TEST
- [ ] can go to a route with an invalid meetingId like /meet/--[90 and it is handled gracefully
- [ ] can go to a meeting where I am not a team member & I am redirected to /invitation-required & someone on the team sees a push invitation
- [ ] can go to /team/--[90 and it is handled gracefully
- [ ] can go to a team I'm not a member of & I'm redirected & someone on the team sees a push notification
- [ ] when i'm on the /invitation-required?meetingId=FOO route & someone accepts my request from a meeting, i go to meeting FOO
- [ ] when i'm on the /invitation-required route & someone accepts my request, i go to the team dash

**Comment by mattkrick** [comment]
fixing bugs by removing code is :fire: 
great work!

**Pull request merged**
