### PR TITLE
fix: add billing info

### PR DESCRIPTION
**Pull request by nickoferrall**
Fix https://github.com/ParabolInc/parabol/issues/6963

### To test

- [ ] If a credit card is linked to the org, the message on the upcoming invoice panel says, "Card will be charged on..."
- [ ] If a credit card is not linked to the org, the message on the upcoming invoice panel says, "Make sure to add billing info..."

### CODE REVIEW

**Comment by mattkrick** [comment]
LGTM! just minor stuff & a merge conflict. feel free to merge when ready sir!

**Comment by nickoferrall** [comment]
> LGTM! just minor stuff & a merge conflict. feel free to merge when ready sir!

@mattkrick great! I've fixed the merge conflict but I don't see comments about the minor stuff?

**Review by mattkrick — CHANGES_REQUESTED** [review]

**Comment by mattkrick** [comment]
didn't submit the review, now they're there!

**Comment by nickoferrall** [comment]
Thanks!

**Pull request merged**
