### PR TITLE
fix: Accepting team invitation updates correctly on other tabs

### PR DESCRIPTION
**Pull request by jmtaber129**
# Description

Fixes https://github.com/ParabolInc/parabol/issues/8090

See https://github.com/ParabolInc/parabol/issues/8090#issuecomment-1525861778 for additional context.

## Testing scenarios
See https://github.com/ParabolInc/parabol/issues/8090#issuecomment-1525861778 for repro steps.
- [ ] Run repro steps on `master` and confirm issue is present
- [ ] Run repro steps on this PR and confirm issue is resolved.

## Final checklist

- [X] I checked the [code review guidelines](../docs/codeReview.md)
- [X] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [X] I have performed a self-review of my code, the same way I'd do it for any other team member
- [X] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [X] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [X] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [X] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by mattkrick** [comment]
yikes! what a bug. `field` should always be present, if it's not, we've got a bigger problem on our hands & this would hide that problem.

Would you mind digging into this a little more so we can find a root cause?

**Comment by mattkrick** [comment]
tried to reproduce this, looks like user A (mutator) gets a server error, user A (subscriber) gets the error mentioned, and user B gets another error! 

The server error looks like this: `Cannot return null for non-nullable field Team.(agendaItems,agendaItems)` which means the server isn't using the updated JWT

**Comment by mattkrick** [comment]
whoaaaa root cause was the fragment `AcceptTeamInvitationMutation_notification` was never included in the notification subscription even though we called its updater!
It never threw an error before the relay upgrade because it was silently failing. That means anyone who accepted a team invitation would only accept it for their first tab, not their other open tabs/browsers/clients! This must've been an error for _years_!
 
Now with the relay upgrade & the return payload is nested, this error made it past the nullish `payload` check.

**Comment by jmtaber129** [comment]
Closing in favor of https://github.com/ParabolInc/parabol/pull/8127

**Pull request closed without merging**
