### PR TITLE
fix: support documentation easier to find in-app

### PR DESCRIPTION
**Pull request by gitstart**
# Description

Fixes/Partially Fixes #[7055](https://github.com/ParabolInc/parabol/issues/7055)

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

### Screen Shot
chrome_iXoc4vw2ZV

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [x] Scenario
- Step 1
   Ensure "Teamwork Resource" was changed to Documentation and points to Support page

-  Step 2
   Ensure "Give Feedback" is changed to "Get Help" and links to Contact Form

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by Dschoordsch** [comment]
Is there an issue for this change? Can you please link it in the description?

**Comment by gitstart** [comment]
> Is there an issue for this change? Can you please link it in the description?

@Dschoordsch done

**Comment by jmtaber129** [comment]
@gitstart can you please fill out the template with screenshots + testing scenarios?

**Comment by jesjo001** [comment]
> # Description
> Fixes/Partially Fixes #[7055](https://github.com/ParabolInc/parabol/issues/7055)
## Issue - Enhancement
> We offer two kinds of support: **- Documentation:** Sometimes called 'proactive support', we had write ups on how to do common things in the product, these are published here: https://www.parabol.co/support/ **- Email or Chat support:** If users have a question that's not answered in the support docs, they can reach out to us directly via email or chat. The form is here: https://www.parabol.co/contact/
> 
> We currently don't surface these options within the product. In general, we believe the product is easy-to-use and intuitive, so there likely won't be many cases of folks needing to reach out to us.
> 
> But if they do, I think it should be easier to figure out how.
> 
> Here's what I propose: Screen Shot 2022-08-11 at 11 31 24 AM
> 
> * Change 'Teamwork Resources' to 'Documentation' or similar, and point to the Support page above: The resources on our site are more general education, where I imagine folks clicking into this menu have a specific question they want answered
> * Change 'Give Feedback' to 'Get help' link, pointing to the Contact form: 'Give Feedback' currently points to the support pages, which I think is unexpected. Instead, it should have a clearer label and go to where folks could actually get help.
> 
> ### Acceptance Criteria (optional)
> Users can access support documentation and the support form from within the app.
> 
> **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

> ## Testing scenarios
> [Please list all the testing scenarios a reviewer has to check before approving the PR]
> 
> * [x]  Scenario A
>   
>   * Step 1
>    Ensure "Teamwork Resource" was changed to Documentation and points to Support page
>   * Step 2
>    Ensure "Give Feedback" is changed to "Get Help" and links to Contact Form

> ## Final checklist
> * [x]  I checked the [code review guidelines](../docs/codeReview.md)
> * [x]  I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
> * [x]  I have performed a self-review of my code, the same way I'd do it for any other team member
> * [x]  I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
> * [x]  Whenever I took a non-obvious choice I added a comment explaining why I did it this way
> * [x]  I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
> * [x]  PR title is human readable and could be used in changelog

**Comment by gitstart** [comment]
@jmtaber129  testing scenario and screenshot updated

**Review by jmtaber129 — APPROVED** [review]

**Pull request merged**
