### PR TITLE
Run prettier after pg:build

### PR DESCRIPTION
**Pull request by Dschoordsch**
Having all generated files in the wrong format is distracting during
development. Also format files which weren't correctly formatted.

### CODE REVIEW

**Comment by mattkrick** [comment]
mmm that's probably the right way to do it!
i was focused on trying to get our commit hooks to ignore those files but that was a losing battle!

Now if only pgtyped deterministically sorted their string unions :sweat: 
If you wanted to PR that codebase I wouldn't mind!

**Comment by Dschoordsch** [comment]
I would prefer not to format generated files, I just figured as these are mostly formatted, that it was intentional. I will try to ignore those instead.

**Review by tiffanyhan — APPROVED** [review]
thanks for putting some attention on this. i usually just check in the generated files that i was working on, then restore the rest in git. it's a pesky annoyance though.  i'm good with this fix, but would also prefer #5292 if we can get the `.prettierignore` file to work and not format the generated files on save.

**Comment by mattkrick** [comment]
closing as we're just ignoring these from now on :tada:  #5292

**Pull request closed without merging**
