### PR TITLE
Updated logo files (styles, static, and S3)

### LINKED ISSUE #4283: Logo updated in app
We’re moving from the all-caps to the all-lowercase

### Acceptance criteria
- Logos updated (including any AWS, or maybe all air-gapped?)
- Added new logo lockup in white for the header to avoid palette change
- Added new logo mark in current palette in other places
  - App emails (e.g. summary etc.)
  - Meeting sidebar
  - Scrubbed for others

### Estimated effort
- 4 hours

### PR DESCRIPTION
**Pull request by ackernaut**
Fixes  #4283 
### Tests
Adds new logo variants in the following places:
- [x] Auth page (styles SVG)
- [x] Dashboard header (styles SVG)
- [x] Meeting navigation sidebar (styles SVG)
- [x] Loader (spinner, updated shape paths)
- [x] Basic email header (email-header-branding-color variants, static and S3)
- [x] Summary email header (mark-purple at 3x.png, static, S3)
- [x] Summary email footer (mark-color at 3x.png, static, S3)
- [x] Favicon (.png and .ico, static and on S3)
- [x] Apple touch icon (static, S3)
- [x] Web app manifest icons (192x192, 512x512 files updated on S3)

### CODE REVIEW

**Comment by ackernaut** [comment]
@nickoferrall mind giving this a review?

**Comment by nickoferrall** [comment]
### Tests

- [ ]  Auth page (styles SVG)
- [ ]  Dashboard header (styles SVG)
- [ ]  Meeting navigation sidebar (styles SVG)
- [ ]  Loader (spinner, updated shape paths)
- [ ]  Basic email header (email-header-branding-color variants, static and S3)
- [ ]  Summary email header (mark-purple at 3x.png, static, S3)
- [ ]  Summary email footer (mark-color at 3x.png, static, S3)
- [ ]  Favicon (.png and .ico, static and on S3)
- [ ]  Apple touch icon (static, S3)
- [ ]  Web app manifest icons (192x192, 512x512 files updated on S3)

**Comment by nickoferrall** [comment]
> @nickoferrall mind giving this a review?

Sure thing! It looks like the changes in this PR include recent changes on `master`. I _think_ if you change the base branch from master to staging and then back to master, it will only show the changes that you've made.

The updates on the auth page and the dashboard look great. Are all of the changes visibly different or are some just changes to the file type. For example, for the favicon, I can't see a difference between this branch (left) and the one in prod (right) below:

favicons

You mentioned `(.png and .ico, static and on S3)` so perhaps this one is just a change to the file type?

**Comment by ackernaut** [comment]
@nickoferrall thanks for looking:
- My work from #4653 which improves the layout of the template select button was approved and merged into this branch unintentionally (I was running without needed SVG files so I branched from here). We can ignore about 5 files related to the template dialog
- The changes to the mark itself are hard to see. The gap between the elliptical shapes is wider. So it was mostly swapping files and I refined dimensions a little as there were nuances in whitespace on the image, etc.

If everything looks in order I’d like to get this in.

**Review by nickoferrall — APPROVED** [review]
@ackernaut OK great, thanks for clarifying. Looks good to me!

**Pull request merged**
