### PR TITLE
Limit number of dashboard avatars

### PR DESCRIPTION
**Pull request by nickoferrall**
PR to resolve issue #4566 

This PR: 

- dynamically calculates the max number of avatars that should be displayed on the dashboard
- if there's not enough space for all avatars, an overflow avatar is displayed 

In the issue I mentioned that we could hover over the overflow avatar which says +7 and a dropdown menu would show the 7 missing avatars. This dropdown behaviour doesn't exist in the new meeting view or poker view so, for consistency, I haven't added a dropdown menu to the dashboard.

### To test

Create a large number of meeting members. I did this by adding a new line below 59, adding `const test = [...teamMembers, ...teamMembers, ...]` and replacing `teamMembers` in lines 61-62 with `test`.

- [ ] When there's not enough space for all of the team member avatars, show an overflow avatar
- [ ] There's no horizontal scrollbar
- [ ] Overflow avatar shows the correct number of missing avatars

### CODE REVIEW

**Comment by mattkrick** [comment]
Screenshot from 2021-03-31 11-52-20

AC
- [ ] no scrollbar appears, we just show the overflow avatar
- [ ] the online badge is not clipped for the right-most avatar
- [ ] the add team member icon is always on the left
- [ ] settings & integrations is on the same line as the org

**Comment by nickoferrall** [comment]
Thanks, I've just pushed an update. 

I haven't been able to reproduce the add team member icon not being on the left - the latest update has the icon on the left on all breakpoints in Chrome & Safari. 

I think the clipped right-most avatar is caused by the horizontal-scroll. Now that I've removed that, it should no longer be clipped.

**Comment by ackernaut** [comment]
Looking now…

**Review by ackernaut — APPROVED** [review]
Sorry for the delay here! I got pulled away obviously. Everything looks as outline above, including the fixes.

Feel free to merge when you’re ready @nickoferrall and excellent work! 👏

**Comment by nickoferrall** [comment]
Thanks Terry!

**Pull request merged**
