### PR TITLE
fix: AdjustMeetingMemberCountPosition

### PR DESCRIPTION
**Pull request by gitstart**
# Description
Fixes/Partially Fixes [issue](https://github.com/ParabolInc/parabol/issues/6060)
[Please include a summary of the changes and the related issue]

If there are too many meeting member avatars to fit in the meeting card, the meeting member count avatar can float away from the card.
image

[loom video](https://www.loom.com/share/852d745e358b4501adceed7b1d43beae)

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by gitstart** [comment]
@Dschoordsch, @igorlesnenko  this PR is Up for review.

**Comment by JimmyLv** [comment]
@gitstart  Could you please help to add a Loom video for the fixed demo?

**Comment by gitstart** [comment]
> @gitstart Could you please help to add a Loom video for the fixed demo?

Hi @JimmyLv,  a loom video has been appended to the description, you can check it out.

**Review by JimmyLv — APPROVED** [review]
Thanks! Looks good!

**Review by Dschoordsch — APPROVED** [review]
Works, nice work!

**Pull request merged**
