### PR TITLE
Remove postdeploy migrations

### LINKED ISSUE #5374: Remove postdeploy migrations pattern
Today, we have both predeploy & postdeploy migrations for postgres.
This is a little confusing & still doesn't save us from race conditions (because code can complete for up to 60 seconds on the old container).
It's also been misused, with some migrations exist it in even though they change the schema.
This leads to confusions as it's hard to track down where a change happened & means extra steps when getting the repo set up.

AC
- [ ] `yarn postdeploy` script is removed
- [ ] from an empty repo, can run `yarn dev` and it works (this means we add new migrations to the regular migrations folder)
- [ ] from a repo with prod data, can run  `yarn dev` and it works (this means the new migrations don't throw errors if something already exists)

Estimate: 2 hours

### PR DESCRIPTION
**Pull request by mattkrick**
Fix #5374

TEST
- [ ] from a clean repo clone, go through the readme steps & start the app. it works!
- [ ] from a clean repo clone, copy a slice of the prod rethinkdb database & a slice of the pg database (or the whole thing if you can't take a slice of PG) & start the app. it works!

### CODE REVIEW

**Comment by mattkrick** [comment]
@nickoferrall would you be so kind as to test this & see if it fixes the issue?

note: you may get borks if old teams refer to meeting templates that don't exist in your instance of PG. If that happens, you'll still have to clone PG from prod first

**Comment by nickoferrall** [comment]
Sure thing!

I've taken the folllowing steps:
- cloned the repo again
- checked out your branch
- updated the `sharp` package to 0.28.0, samlify to 2.7.7, and added `platform: linux/amd64` to the docker-compose.yml file (this is required for the m1 chip; I'll create a PR with these changes once this PR is working for me) 
-  followed the Readme steps being: copy env, `yarn`, `yarn db:start`, `yarn dev`
- then get the following error:

```
### MIGRATION 1626823580960_taskEstimate (UP) ###
#> WARNING: This migration is not wrapped in a transaction! <
### MIGRATION 1627394777775_addPollsTable (UP) ###
### MIGRATION 1631040185256_uniqueEmail (UP) ###
/Users/nickoferrall/parabol-2/parabol/node_modules/@pgtyped/query/lib/preprocessor-sql.js:81
                        const val = entity[pickKey];
                                          ^

TypeError: Cannot read property 'id' of null
    at /Users/nickoferrall/parabol-2/parabol/node_modules/@pgtyped/query/lib/preprocessor-sql.js:81:43
    at Array.map (<anonymous>)
    at /Users/nickoferrall/parabol-2/parabol/node_modules/@pgtyped/query/lib/preprocessor-sql.js:80:26
    at Array.map (<anonymous>)
    at Object.exports.processSQLQueryAST (/Users/nickoferrall/parabol-2/parabol/node_modules/@pgtyped/query/lib/preprocessor-sql.js:77:22)
    at PreparedQuery.<anonymous> (/Users/nickoferrall/parabol-2/parabol/node_modules/@pgtyped/query/lib/tag.js:36:76)
    at Generator.next (<anonymous>)
    at /Users/nickoferrall/parabol-2/parabol/node_modules/@pgtyped/query/lib/tag.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nickoferrall/parabol-2/parabol/node_modules/@pgtyped/query/lib/tag.js:4:12)
    at PreparedQuery.run (/Users/nickoferrall/parabol-2/parabol/node_modules/@pgtyped/query/lib/tag.js:35:44)
    at up (/Users/nickoferrall/parabol-2/parabol/packages/server/postgres/migrations/1631553388387_add-template-teams-users.ts:26:44)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Migration._apply (/Users/nickoferrall/parabol-2/parabol/node_modules/node-pg-migrate/dist/migration.js:117:13)
    at async exports.default (/Users/nickoferrall/parabol-2/parabol/node_modules/node-pg-migrate/dist/runner.js:176:13)
error Command failed with exit code 1.
```

I've checked to see whether there are any relevant issues in pgtyped but I haven't found anything yet. Perhaps the new `uniqueEmail` migration could be causing the issue?

**Comment by mattkrick** [comment]
from the stack trace i see

```
    at up (/Users/nickoferrall/parabol-2/parabol/packages/server/postgres/migrations/1631553388387_add-template-teams-users.ts:26:44)
```

so pg typed is running in a migration, which is OK, but we never ran `yarn pg:build`

could you try again but run `yarn pg:build` after running `yarn` and see if that fixes it? that may be something we'll need to add to the readme

**Comment by nickoferrall** [comment]
I haven't had the chance to dig-in in much detail but here's a progress update: I've cloned again, followed the Readme steps, and ran a `yarn pg:build` but I get an error with the recent `add-template-teams-users` (see first screenshot). 

After removing that file, I ran into the error in the second screenshot. I ran `yarn postmigrate` and `yarn dev` and was able to sign-in but ran in into the old error of `Cannot return null for non-nullable field ReflectTemplate.(team,team,team,team)` when starting a meeting. I'll look into the first error in more detail on Friday!

err
err-2

**Comment by mattkrick** [comment]
ahhh! i _think_ this was fixed in my latest commit if you do a fresh pull

**Comment by mattkrick** [comment]
merging to master as worst case scenario is it is just broken as before

**Comment by nickoferrall** [comment]
@mattkrick I've freshly cloned the repo, pulled from `master`, upgraded `samlify` and `sharp` modules for the m1 chip, and followed the readme steps, but I'm now getting an error in the recently updated `upsertGitHubDimensionFieldMapQuery` that `relation "GitHubDimensionFieldMap" does not exist`.

Here's what I get when I run `yarn pg:build`:

fieldMap

And when I run `yarn dev`:

null-id

Do you think the `upsertGitHubDimensionFieldMapQuery` needs updating to create that relation or is there something I can do on my end?

**Pull request merged**
