### PR TITLE
feat: make gitlab url dynamic for onprem gitlab

### PR DESCRIPTION
**Pull request by adaniels-parabol**
Make gitlab url part of env vars so it can be set for onprem instance of gitlab

### CODE REVIEW

**Comment by mattkrick** [comment]
Would this expose our githlab client secret with the PPMI? 
we've got a mutation for adding a self-hosted gitlab: https://github.com/ParabolInc/parabol/blob/9177909d9b3bc9cf2ba5d88a32c0ce53b1da177f/packages/server/graphql/mutations/addIntegrationProvider.ts. 

I'm not sure if it's all the way hooked up yet, but that's the pattern.

**Comment by adaniels-parabol** [comment]
> Would this expose our githlab client secret with the PPMI? we've got a mutation for adding a self-hosted gitlab: https://github.com/ParabolInc/parabol/blob/9177909d9b3bc9cf2ba5d88a32c0ce53b1da177f/packages/server/graphql/mutations/addIntegrationProvider.ts.
> 
> I'm not sure if it's all the way hooked up yet, but that's the pattern.

Thus far no one has request gitlab integration on PPMI. This was for self-hosted, I wanted an option to set the URL for this reason. It seems like this would be an easier method? However, I don't mind trying the other integration. Can you give an example of how we'd enable it?

Note on self-hosted or PPMI if they wanted to use gitlab they would add an app to their instance and get client_id and client secret for their environment.

**Comment by mattkrick** [comment]
yeah, either webhook or oauth2, I forget which one gitlab likes to use. it takes a few extra fields, but it looks like this:

```gql
mutation {
  addIntegrationProvider(input: {oAuth2ProviderMetadataInput: {serverBaseUrl: "htpp://foo.co", clientId: "abc", clientSecret: "Shhh"}})
}
```

**Comment by mattkrick** [comment]
closing this in favor of https://github.com/ParabolInc/parabol/issues/6051. Uncle Sam is asking for this, so it's gonna happen!

**Pull request closed without merging**
