### PR TITLE
refactor: Set `updateAt` field via a Postgres trigger

### PR DESCRIPTION
**Pull request by shapel**
As part of #6239 struggle, we encountered the fact that Postgres & RethinkDB store "Team" records with `updatedAt` that differ by about a year.  This appears to be because the system does not always update the `updatedAt` field of Postgres or RethinkDB in some cases.
As @Dschoordsch suggested at https://github.com/ParabolInc/parabol/pull/6239#discussion_r863542513 this PR adds triggers for all tables that have `updateAt`.

### CODE REVIEW

**Comment by shapel** [comment]
👋 @tianrunhe could you review this?

**Comment by shapel** [comment]
Hello @tianrunhe, just pinging to make sure that it's on your radar 🤞

**Review by tianrunhe — CHANGES_REQUESTED** [review]
GREAT work! Thanks so much for doing this!

I only have 1 suggestion: why not combine all of the migrations into one? It'll be faster to execute during deployment.

**Comment by shapel** [comment]
@tianrunhe thanks for review.
I did what you suggested + rebase master

**Review by tianrunhe — APPROVED** [review]
LGTM! Thanks again for doing this!

**Review by Dschoordsch — APPROVED** [review]
Thanks for taking this on!

**Pull request merged**
