### PR TITLE
chore: Weekly review stats in Slack

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Let's run review stats on a regular basis. The previously used review stats package had 2 major disadvantages:
1) it calculated time to review wrong
2) it requires monthly sponsorship to be able to post to Slack
Grep the PR timeline for PRs merged in the last 7 days and calculate the time to review etc. from those.

## Demo

Screenshot from 2022-09-20 12-27-18

## Testing scenarios

* create GitHub personal access token with `public_repo` right
* if you want to check Slack, you need to create a bot with a webhook, otherwise stats will be printed on console but pushing to slack will fail
* export following environment variables
  ```
  GITHUB_TOKEN=<your personal access token>
  TIME_DIFF=<defaults to 7d if not set>
  SLACK_WEBHOOK=<your channel webhook>
  REPO=ParabolInc/parabol
  ```
* run `yarn ts-node scripts/reviewStats.ts`

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by Dschoordsch** [comment]
Possible improvement: Matt doesn't appear in the example stats although he did reviews because he did not approve but merged straight away.

**Review by nickoferrall — APPROVED** [review]
I'm running into a permissions error with my GitHub personal access token when testing locally, but as this isn't customer-facing and it has already worked in Slack, I think it's safe to approve!

If it's a quick change, I think it'd be helpful to sort the table by "Median time to approve" as that's the main stat we're focusing on at the moment

**Comment by Dschoordsch** [comment]
> I'm running into a permissions error with my GitHub personal access token when testing locally, but as this isn't customer-facing and it has already worked in Slack, I think it's safe to approve!
Did you add `public_repo` rights?
 
> If it's a quick change, I think it'd be helpful to sort the table by "Median time to approve" as that's the main stat we're focusing on at the moment
I added sorting and also weekend compensation and I consider merge by non-author as a review now.

**Review by BartoszJarocki — APPROVED** [review]
nice work! 
Screenshot 2022-09-20 at 15 14 14

**Pull request merged**
