### PR TITLE
chore(suggest-groups): increase number of suggested groups

### PR DESCRIPTION
**Pull request by nickoferrall**
Fix https://github.com/ParabolInc/parabol/issues/8621

Here's a long-winded demo where I look through the reflection groups from the recent Growth Retro: https://www.loom.com/share/41e45efd828d49378db820582d6b4423

### To test

- [ ] Create a couple of Retros, click Suggest Groups, and get suggested groups that are at least as useful as the previous prompt

### CODE REVIEW

**Comment by tghanken** [comment]
@nickoferrall Did you intend to link a demo here?

**Comment by nickoferrall** [comment]
Sorry @tghanken, PR description updated!

**Review by tghanken — APPROVED** [review]
Safe to merge as is, I'm getting results at least as good as our prior implementation.

+1 I'd like to see us encourage the AI to not group a reflection where there's a low certainty.  Ex. add some logic to [getThemeForReflection](https://github.com/ParabolInc/parabol/blob/bb481d34338f61ab3758dd699a16b2fb49aadbe7/packages/server/utils/OpenAIServerManager.ts#L151) to allow for a return value that indicates no group should be created for the reflection.

Ex:
```
const prompt = `Given the themes [...] themes I've provided. [NEW] If the reflection does not fit any of the themes, classify the reflection as "noThemeMatch".`
```

**Comment by nickoferrall** [comment]
Originally, I didn't specify how many groups and asked it to only group when they're similar, but it usually results in too many groups IMO.


> If the reflection does not fit any of the themes, classify the reflection as "noThemeMatch".

Here's the results I got after adding the suggested line ^:

Screenshot 2023-08-14 at 15 12 12


I'll merge this PR as it is so that we can get the number of groups improvement. I'd definitely like to spend more time improving the prompt as I'm sure it could be better.

**Pull request merged**
