### PR TITLE
feat: Add meetings to the team dashboard

### LINKED ISSUE #8502: Show meetings in Team dashboard
As a user with multiple teams, I want to see my meetings by team easily.

## Acceptance criteria
* [ ] Add tabs to team dashboard "Activity", "Tasks"
* [ ] "Tasks" contains current task view
* [ ] "Activity" contains the meetings view filtered by this team

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

Fixes #8502 
Add a tab for meetings to the team dashboard. The default view is still "Tasks" to not interrupt users habits too much.

## Demo

https://www.loom.com/share/d3a5e74fd16842d387c59648f3539a48?sid=92906de6-0297-4f1e-b09d-bb9c62e9fe48

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [ ] open team dashboard
- [ ] switch between tabs
- [ ] try different filters
- [ ] open a meeting
- [ ] check the sidebar highlight

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by Dschoordsch** [comment]
@acressall I used the existing tabs instead of designing the component exactly like in the design. Same for the empty meeting cards. Can you check if that's ok?

**Comment by acressall** [comment]
@Dschoordsch I think using the existing elements is fine! Looks good! My only hesitation is defaulting to the tasks view. When I create a new team, will it still default to tasks? I think activity would be the more useful. 

I agree that showing tasks first creates consistency for existing users, but it doesn't add any value for new users (and might be confusing since you'd be starting on the _second_ tab). We also know that not all teams use tasks, so the activity tab might be the more generally useful for everyone. WDYT?

**Comment by Dschoordsch** [comment]
@acressall No strong feelings either way. I think if we default to the activity, we should explicitly link to the tasks dashboard from the summary page: The meeting just ended, so likely there is nothing to see in the activity, but you might just have some new tasks. I'm not sure if there are other links to the team dashboard to consider.

**Comment by acressall** [comment]
> I think if we default to the activity, we should explicitly link to the tasks dashboard from the summary page: The meeting just ended, so likely there is nothing to see in the activity, but you might just have some new tasks. I'm not sure if there are other links to the team dashboard to consider.

Yes, let's link to the tasks tab from meeting summary. I think the context of that makes sense. 
The only other link to the team dash I can think of is when you're in a meeting it says the team name in the menu and that's clickable. In that case I think it makes sense to go to the activity tab, so you can get back to the meeting if you need to.

**Comment by Dschoordsch** [comment]
@igorlesnenko I changed the default to the activity tab, just like @acressall suggested. Any objections?

**Pull request merged**
