### PR TITLE
adding copy to the authentication page

### PR DESCRIPTION
**Pull request by acressall**
Adding copy to the authentication page for improved SEO

### CODE REVIEW

**Comment by acressall** [comment]
@avivapinchas is this still the copy you want here? I see it was written 2yrs ago and we have just spent some time updating our brand positioning!

> Free online retrospectives that get teams talking
> Make your good team great by sharing feedback, deciding on what to do, and continuously improving. Parabol is Free and Open Source, so there's nothing standing between you and better teamwork.

The current copy is also a bit long on mobile, where it pushed the login further down. It's not a big deal, but I'd love to get another field in view since that's what people are coming here for – WDYT?
Screen Shot 2022-02-23 at 12 26 51 AM

**Comment by avivapinchas** [comment]
Thanks for checking! That's reallllly outdated copy. I think we should just make it match the homepage, since that's our latest: 

> Better Meetings, Less Effort
> Help your team connect & improve with an agile meeting co-pilot

**Comment by acressall** [comment]
Copy updated! Looks so clean 😄 
Screen Shot 2022-02-23 at 7 14 48 PM

**Review by ackernaut — APPROVED** [review]
LGTM

**Pull request merged**
