### PR TITLE
feat: text align center for icebreakers

### LINKED ISSUE #8193: Icebreaker: Align center icebreakers
Icebreakers are currently aligned left, which creates a lack of balance on the page. 

We could align all icebreaker text to be centralised, creating more harmony on the page.

### PR DESCRIPTION
**Pull request by BartoszJarocki**
# Description

Fixes #8193 

## Demo

Screenshot 2023-06-01 at 08 14 32

## Testing scenarios

- [ ] See if the icebreaker question text is center aligned 

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by BartoszJarocki** [comment]
@enriquesanchez do you mind checking what can we do here with regards to @jmtaber129 comment? any thoughts?

**Comment by enriquesanchez** [comment]
A quick one: we could move the edit and refresh buttons below the text (and add a label to each for good measure).

A better one: style the icebreaker like a card (similar to icebreakers.parabol.co) which would add structure to it and help us make it look more balanced.

@jmtaber129 @BartoszJarocki Of those two, which one sounds better to you? Let me know and I can mock up something.

**Comment by enriquesanchez** [comment]
>we're discussing a case, that happens only for a facilitator

This is a great reminder @BartoszJarocki

**Comment by enriquesanchez** [comment]
>we're discussing a case, that happens only for a facilitator

With the above in mind and for the sake of keeping this short and simple let's just center align them at the bottom:

image

**Comment by BartoszJarocki** [comment]
Screenshot 2023-06-12 at 13 09 31

@enriquesanchez changed the implementation and it looks now like ☝️ I also added a tooltip for refresh action, as it was missing.  CC @jmtaber129

**Comment by enriquesanchez** [comment]
@BartoszJarocki I like it!

**Pull request merged**
