### PR TITLE
new meeting snackbar

### LINKED ISSUE #3650: Added snackbar for recently started meetings
### Acceptance Criteria
- See [concept in Figma](https://www.figma.com/file/mN1tnQnNR8ZeY1W7Q0zOA6/2019-App-IA?node-id=429%3A8324)
- A snackbar appears over any dashboard view when a meeting has started LT 5 minutes ago
- Copy variant ideas:
  - The MEETING_NAME meeting started just now. Join Meeting
  - The MEETING_NAME meeting started N minutes ago. Join Meeting
- The snackbar goes away when 5 minutes have elapsed
- When 2+ meetings have started LT 5 minutes ago, the snackbar shows the oldest one to avoid changing the context on the user without them catching it OR come up with a better heuristic

### Estimated Effort
- 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### PR DESCRIPTION
**Pull request by mattkrick**
fix #3650 

TEST
- [ ] user 1 starts a meeting
- [ ] user 2 goes to the dash, sees the meeting in a snack
- [ ] user 1 sees the meeting in a snack on the dash
- [ ] if they click the button on snack they can join

Signed-off-by: Matt Krick <matt.krick@gmail.com>

### CODE REVIEW

**Comment by mattkrick** [comment]
@ackernaut ready for review!

**Comment by ackernaut** [comment]
### Test cycle no. 1
- [ ] user 1 starts a meeting
- [  ] user 2 goes to the dash, sees the meeting in a snack
- [ ] user 1 sees the meeting in a snack on the dash
- [ ] if they click the button on snack they can join

**Comment by ackernaut** [comment]
@mattkrick I thought the snackbar was going to persist until the 5-min mark passed. It goes away pretty quick after initial load. Thoughts?

**Comment by mattkrick** [comment]
ahh, i was thinking it would appear if a meeting had been created 5 mins ago.
bumped it up to stick around for 15 seconds

**Pull request merged**
