### PR TITLE
fix(al): Speedup subcategory resolver

### PR DESCRIPTION
**Pull request by jmtaber129**
# Description

See https://parabol.slack.com/archives/C836NA350/p1690212940822539

The logic implemented for certain subcategories in https://github.com/ParabolInc/parabol/pull/8413 is pretty slow (especially in production), so refactor the logic a bit to speed it up.

Specifically, instead of fetching a bunch of meetings (which can take on the order of seconds), do a map-reduce to find the last usage time for each `[teamId, templateId]` tuple (which takes on the order of 10s of milliseconds).

## Testing scenarios
- [ ] On master, ensure each of the retro subcategories are populated on the retro tab ("popular", "recently used by you", "others in your org are using", "you should try", and "other")
- [ ] Switch to this branch, and reload the retro page. Verify that the same templates are in each category.
- [ ] Verify that navigating to and refreshing the AL is fast.

## Final checklist

- [X] I checked the [code review guidelines](../docs/codeReview.md)
- [X] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [X] I have performed a self-review of my code, the same way I'd do it for any other team member
- [X] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [X] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [X] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [X] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by mattkrick** [comment]
Going from seconds to ms is huge, nice work!
I benchmarked this for my user in the admin panel & it came in at ~50ms, so it's certainly a speedup!
Even 50ms is still a pretty long query though.
Datadog shows that each executor runs this 400-500x/day. 
So 50ms * 500 = 25 seconds total run time per executor per day. Not terrible, but certainly in the top 10 hottest postgres queries we've got (we don't have data for RethinkDB queries so it's not strictly apples to apples).
For context, most queries complete in under [10ms](https://app.datadoghq.com/apm/services/gqlexecutor_6-postgres/operations/pg.query/resources?env=production&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap99%29%2CtopN%3A%215%29%2Cversion%3A%210%29&sort=p50%2Cdesc&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A75%29%2Cdistribution%3A%28isLogScale%3A%21f%29%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Acount%2CbreakdownAs%3Apercentage&start=1690295708656&end=1690310108656&paused=false).


Some ideas for speeding it up:
- If you can change the business logic, exclude public templates from the "recently used" category. That way, you can use `template.lastUsedAt`, which would eliminate the query entirely
- store teamId:templateId->lastUsedAt field in PG or redis. it's extra complexity, but <1ms read times. If you take this route, I'd suggest having category be the parent of the template (e.g. a gql fetch will be like `categories { template { id } }` instead of `template { subCategory }`, or just make the dataloader fetch for the whole team. That'll reduce the fetch from O(n) to O(1).

**Comment by jmtaber129** [comment]
@mattkrick I definitely agree that 50ms is still a long query, and we'll probably want to cache this in redis in the long term, but I'm not sure the added complexity+effort is worth the performance improvements _yet_, since this is still a relatively experimental feature. That first suggestion wouldn't quite work because we're looking for `lastUsedAt` for specific teams - i.e. when did `viewer`'s team last use the template, vs. when was the template last used by _anyone_. We also still want to show recently used public templates.

I'd prefer to get this landed with this approach, and then check the GQL query's real-world performance in datadog compared to `NewMeetingQuery` to decide whether additional perf improvements are necessary. If I'm reading the datadog stats correctly, a 50ms p50 would put this GQL query at just under 2x that of `NewMeetingQuery`.

**Comment by mattkrick** [comment]
You're completely right! The important distinction is that `NewMeetingQuery` includes _everything_ to make that query a success: time spent on the webserver, redis queries, PG queries, and a handful of other RethinkDB queries. I dug up a breakdown in DD [here](https://app.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3Aproduction%20resource_name%3A%22query%20NewMeetingQuery%22&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&graphType=flamegraph&highlight=gqlexecutor_5&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=9172946587051527326&spanType=service-entry&timeHint=1690296684438&trace=AgAAAYmNiI-WfusHegAAAAAAAAAYAAAAAEFZbU5pSlRQQUFEN1V3cVRmTWxCMFdNMwAAACQAAAAAMDE4OThkYzctNTQzZS00ZWQ4LWJjMDItOGFiZjQ5MmYxZTIy&traceID=3991164098269461448&start=1690241509817&end=1690327909817&paused=false). I'm assuming resolving `teamTemplates` is probably the closest thing we can compare to, which is ~4ms, but a direct would be even better! So let's look at the query for [ActivityLibrary](https://app.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3Aproduction%20resource_name%3A%22query%20ActivityLibraryQuery%22&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=3970531436290911942&spanType=service-entry&timeHint=1689725511435&trace=AgAAAYlrfScLyq_Q0AAAAAAAAAAYAAAAAEFZbHJmVGdOQUFEMnB0MVo2WmdwbGFSSQAAACQAAAAAMDE4OTZjNGUtMDI3My00ODIxLWI1ZTktNTgxMzAxODE0MzFj&traceID=5234423626072898427&start=1689724412723&end=1690329212723&paused=false).

If we reduce that 3990ms to 50ms we're still at ~120ms for the whole query. Not terrible, but if the goal is removing the feature flag we'll need to do better before a few thousand users hammer us with that kind of load.

**Comment by jmtaber129** [comment]
@mattkrick I see, so we may still need to do some additional perf improvements before we can confidently release to GA.

Let's still try to get this landed as-is so we can resolve the user-facing AL loading time issue as part of this week's release (vs. implementing redis caching first and missing this week's release), and then we can prioritize additional perf improvements as planned work as we get ready to remove the feature flag entirely.

**Pull request merged**
