### PR TITLE
fix: add agenda item response handling

### PR DESCRIPTION
**Pull request by shapel**
Fixes how mutation response handling by adding types and fixing possible TypeError (similar to #5383).

### CODE REVIEW

**Comment by shapel** [comment]
👋 @mattkrick do you have a chance to review or assign someone to do this?

**Comment by mattkrick** [comment]
thanks @shapel! 
Do you have some steps I could follow to reproduce the bug?

**Comment by shapel** [comment]
@mattkrick I don't have steps to reproduce. 
I saw that piece of code with potential problem like https://github.com/ParabolInc/parabol/issues/5383 and decided to fix it too. 

PS May be you can to review fix for the issue I mention too?

**Comment by mattkrick** [comment]
LGTM! 🙏

**Pull request merged**
