### PR TITLE
Add CLI to create new mutations

### LINKED ISSUE #3960: CLI to create new mutations
today, new mutations take ~15 mins to bootstrap. We can probably shave 10 mins off & reduce errors by automating it.

i imagine a CLI like `yarn createMutation updateScope Template`. We'll probably use jscodeshift 

Acceptance criteria
- [ ] a CLI takes in: the mutation `name` and the primary object `type`
- [ ] it creates a `server/grahql/mutations/{Name}Payload.ts` file that returns a single `type` in the payload and an empty resolve function
- [ ] it adds the mutation to `rootMutation.ts`
- [ ] it creates a `server/graphql/mutations/{name}.ts` that has a return type of `type`
- [ ] it creates `client/mutations/{Name}Mutation.ts`

Estimate: 8 hours

### PR DESCRIPTION
**Pull request by mattkrick**
fixes #3960

creating a new mutation isn't hard, but there's a lot of ugly boilerplate.
we should get paid to solve hard problems, not do mindless junk.
So, I made a CLI to generate the boilerplate.
we've got about 10 mutations to develop for the next sprint, so this should help.

How to use:
- call the CLI: e.g. `yarn newMutation addSmilesToFriends --subscription team`

How it works:
- this will generate a mutation called `addSmilesToFriends` and connect it to the Team subscription
- if this mutation is going to be hooked up to a subscription, you can add that with a `--subscription` (or `-s`) flag
- it will generate a mutation file on the client & server
- it will generate a mutation payload file on the server
- it will update the rootMutation & rootSubscription on the server
- it will update the client subscription with the mutation fragment

@tianrunhe @tiffanyhan @nickoferrall let me know if this is useful!

### CODE REVIEW

**Comment by mattkrick** [comment]
merging so we can get started with the grip of mutations for the estimate phase

**Comment by nickoferrall** [comment]
@mattkrick amazing! I just gave it a try - this will be really helpful

**Comment by tiffanyhan** [comment]
so cool, thanks for doing this and sharing!

**Comment by tianrunhe** [comment]
oh boy this will make my life much easier!

**Pull request merged**
