### PR TITLE
fix: title of the reflection columns should not be italic 

### PR DESCRIPTION
**Pull request by gitstart**
# Description

Fixes/Partially Fixes #[6436](https://github.com/ParabolInc/parabol/issues/6436)
[Please include a summary of the changes and the related issue]

## Demo

[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain what decisions you've made and under what circumstances]

## Testing scenarios

[Please list all the testing scenarios a reviewer has to check before approving the PR]

- [x] Scenario A
  - Step 1
  - Step 2...

- [ ] Scenario B
  - Step 1
  - Step 2....

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [x] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by gitstart** [comment]
@igorlesnenko this PR is ready for review

**Comment by gitstart** [comment]
@Dschoordsch please can you review this?

**Comment by gitstart** [comment]
@Dschoordsch can you review this?

**Comment by Dschoordsch** [comment]
@enriquesanchez could you take a look if that looks good?
Screenshot from 2022-08-19 16-02-38

**Comment by enriquesanchez** [comment]
Thanks for the ping @Dschoordsch!

The screenshot looks good to me 👍 

Were you able to test if emojis also look OK?

**Comment by Dschoordsch** [comment]
Looks fine
Screenshot from 2022-08-19 17-41-23

**Review by Dschoordsch — APPROVED** [review]

**Pull request merged**
