### PR TITLE
chore(SAML): Improved error message when email attribute is missing

### PR DESCRIPTION
**Pull request by Dschoordsch**
# Description

The most common error with SAML configuration seems to be the email attribute missing from the SAML response. To help debug this situation, list all present attributes in the error message.

## Demo

Screenshot 2023-10-05 at 10 07 46

## Testing scenarios

- [Set up SAML](https://www.loom.com/share/37ef6f0bccc742358987df3ce0c00a96?sid=009af19d-ef68-4646-8649-3709f095fb23) and omit the "email" and "emailaddress" claims

## Final checklist

- [ ] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ ] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [ ] PR title is human readable and could be used in changelog

### CODE REVIEW

**Review by igorlesnenko — COMMENTED** [review]
Code looks good, not tested yet

**Comment by igorlesnenko** [comment]
@Dschoordsch I'm trying to follow your testing guide but not sure I can create an app:
I'm clicking `New application`, but the create my own application  button is inactive.

image

Probably I don't have enough rights, can you give it to me?

**Comment by Dschoordsch** [comment]
@igorlesnenko missed this message, I gave you rights now.

**Comment by mattkrick** [comment]
I don't right owner rights either (https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Members/groupId/21c61fc3-cfc8-4992-ae7f-ddd6e458cce2/menuId/). Code looks good though! feel free to merge without me testing it out

**Review by mattkrick — APPROVED** [review]

**Comment by Dschoordsch** [comment]
@mattkrick I gave you rights as well

**Pull request merged**
