### PR TITLE
chore: update instances of GitLab logo SVG

### LINKED ISSUE #8766: chore: update GitLab logo
The logo exists in a few places:
- Team Integrations view
- Sprint Poker (Scope phase, add the integration tab)
- Task Cards (push to integration)

[Here’s the issue on our internal UX backlog in Notion](https://www.notion.so/parabol/Update-GitLab-logo-1d1a998c7d4f46908a20b54237167c96?pvs=4)

### Acceptance criteria
- Verify any missing places
- Updated the logo in all known places

### Estimated effort
- 4 hours

### PR DESCRIPTION
**Pull request by enriquesanchez**
# Description

Fixes #8766

Updates the GitLab logo [to the new version](https://about.gitlab.com/press/press-kit/).

## Demo

Captura de pantalla 2023-09-05 a la(s) 11 29 43 a m
Captura de pantalla 2023-09-05 a la(s) 11 30 08 a m
Captura de pantalla 2023-09-05 a la(s) 9 58 21 a m

## Testing scenarios

Check new logo is displayed correctly in:

- [ ] Team Integrations view
- [ ] Sprint Poker (Scope phase, add the integration tab)
- [ ] Task Cards (push to integration)

## Final checklist

- [x] I checked the [code review guidelines](../docs/codeReview.md)
- [ ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x] I added the label `One Review Required` if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new patterns and I think one review is sufficient'
- [x] PR title is human readable and could be used in changelog

### CODE REVIEW

**Comment by ackernaut** [comment]
@enriquesanchez does the logo look larger than the others to you? I’m guessing there’s no whitespace around the logo included in the SVG canvas—it probably runs edge to edge?

**Comment by enriquesanchez** [comment]
> does the logo look larger than the others to you? I’m guessing there’s no whitespace around the logo included in the SVG canvas—it probably runs edge to edge?

Ah, you are right! I'll add the whitespace, thank you!

**Comment by enriquesanchez** [comment]
@ackernaut I added the whitespace, looks more balanced now 👍 

Captura de pantalla 2023-09-08 a la(s) 11 46 14 a m

**Review by ackernaut — APPROVED** [review]
Yes, that looks more inline with the rest of them. I think over time in order to get logos feeling balanced I had allowed for a little whitespace on the canvas so some of the logo can be tall or wide or whatever and still feel a similar weight. I’m not sure how much thought goes into logo design considering logos being in the same context as other logos. Nice work!

**Pull request merged**
